// src/pages/session.tsx
import { useState, useEffect, useCallback } from "react";
import { useNavigate, useSearchParams } from "react-router";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { Loader2, ShieldCheck, MailCheck, Languages, HardDrive } from "lucide-react";
import { z } from "zod";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Field, FieldDescription, FieldGroup, FieldLabel, FieldSeparator,
} from "@/components/ui/field";
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

import { useAuthStore } from "@/stores/auth";
import { useSiteConfigStore } from "@/stores/site-config";
import { useRequireGuest } from "@/hooks/use-auth";
import { client } from "@/client";
import { ApiError } from "@disknext/sdk";
import { setLocale } from "@/i18n";

type AuthMode = "login" | "register" | "magic-link";

function getErrorMessage(e: unknown, fallback: string, statusMap?: Record<number, string>): string {
  if (e instanceof ApiError && statusMap?.[e.status]) return statusMap[e.status]!;
  if (e instanceof ApiError && e.message) return e.message;
  if (e instanceof Error) return e.message;
  return fallback;
}

const locales = [
  { code: "zh-CN", name: "简体中文" },
  { code: "en", name: "English" },
  { code: "zh-TW", name: "繁體中文" },
];

export default function SessionPage() {
  useRequireGuest();
  const { t, i18n } = useTranslation();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const setSession = useAuthStore((s) => s.setSession);
  const siteConfig = useSiteConfigStore((s) => s.config);
  const fetchSiteConfig = useSiteConfigStore((s) => s.fetch);

  const [mode, setMode] = useState<AuthMode>("login");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const [tfaRequired, setTfaRequired] = useState(false);
  const [otpCode, setOtpCode] = useState("");
  const [pendingCredentials, setPendingCredentials] = useState<{ email: string; password: string } | null>(null);

  const [magicLinkSent, setMagicLinkSent] = useState(false);
  const [magicLinkVerifying, setMagicLinkVerifying] = useState(false);

  useEffect(() => { fetchSiteConfig(); }, [fetchSiteConfig]);

  // Handle magic link callback
  useEffect(() => {
    const magicToken = searchParams.get("magic_token");
    if (!magicToken) return;
    setMagicLinkVerifying(true);
    client.auth.login({ provider: "magic_link", identifier: magicToken })
      .then((data) => { setSession(data); navigate("/home", { replace: true }); })
      .catch((e) => { setError(getErrorMessage(e, t("session.magicLinkLoginFailed"), { 410: t("session.magicLinkInvalidToken") })); })
      .finally(() => setMagicLinkVerifying(false));
  }, [searchParams, setSession, navigate, t]);

  const submitLogin = useCallback(async (loginEmail: string, loginPassword: string, otp?: string) => {
    setLoading(true);
    setError("");
    try {
      const data = await client.auth.login({
        provider: "email_password",
        identifier: loginEmail,
        credential: loginPassword,
        two_fa_code: otp || undefined,
      });
      setSession(data);
      navigate("/home", { replace: true });
    } catch (e) {
      if (e instanceof ApiError && e.status === 428) {
        setPendingCredentials({ email: loginEmail, password: loginPassword });
        setTfaRequired(true);
        setOtpCode("");
        setError("");
        return;
      }
      setError(getErrorMessage(e, t("session.loginFailedCheck"), { 403: t("session.accountBanned"), 400: t("errors.invalidParams") }));
      if (tfaRequired) setOtpCode("");
    } finally {
      setLoading(false);
    }
  }, [setSession, navigate, t, tfaRequired]);

  const handleLoginSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const result = z.object({
      email: z.string().min(1, t("session.emailRequired")).email(t("session.emailInvalid")),
      password: z.string().min(1, t("session.passwordRequired")),
    }).safeParse({ email, password });
    if (!result.success) { setError(result.error.issues[0]?.message ?? ""); return; }
    submitLogin(email, password);
  };

  const handleRegisterSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const result = z.object({
      email: z.string().min(1, t("session.emailRequired")).email(t("session.emailInvalid")),
      password: z.string().min(1, t("session.passwordRequired")).min(8, t("session.passwordMinLength")),
      confirmPassword: z.string().min(1, t("session.confirmPasswordRequired")),
    }).refine((d) => d.password === d.confirmPassword, { message: t("session.passwordMismatch"), path: ["confirmPassword"] })
      .safeParse({ email, password, confirmPassword });
    if (!result.success) { setError(result.error.issues[0]?.message ?? ""); return; }

    setLoading(true);
    setError("");
    try {
      await client.auth.register({ provider: "email_password", identifier: email, credential: password });
      toast.success(t("session.registerSuccess"));
      await submitLogin(email, password);
    } catch (e) {
      setError(getErrorMessage(e, t("session.registerFailed"), { 409: t("errors.conflict"), 400: t("errors.invalidParams") }));
    } finally {
      setLoading(false);
    }
  };

  const handleMagicLinkSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const result = z.object({ email: z.string().min(1, t("session.emailRequired")).email(t("session.emailInvalid")) }).safeParse({ email });
    if (!result.success) { setError(result.error.issues[0]?.message ?? ""); return; }
    setLoading(true);
    setError("");
    try {
      await client.auth.sendMagicLink({ email });
      setMagicLinkSent(true);
    } catch (e) {
      setError(getErrorMessage(e, t("errors.loginFailed"), { 400: t("errors.invalidParams"), 429: t("errors.fetchFailed") }));
    } finally {
      setLoading(false);
    }
  };

  const handleOtpSubmit = () => {
    if (!pendingCredentials || otpCode.length !== 6) return;
    submitLogin(pendingCredentials.email, pendingCredentials.password, otpCode);
  };

  const cancelTfa = () => { setTfaRequired(false); setPendingCredentials(null); setOtpCode(""); setError(""); };
  const switchMode = (m: AuthMode) => { setMode(m); setError(""); setMagicLinkSent(false); };

  const registerEnabled = siteConfig?.register_enabled ?? false;
  const magicLinkEnabled = siteConfig?.auth_methods?.some((m) => m.provider === "magic_link" && m.is_enabled) ?? false;
  const showAgreement = !!(siteConfig?.tos_url || siteConfig?.privacy_url);

  // --- Special states (full-screen centered cards) ---

  if (magicLinkVerifying) {
    return (
      <CenteredWrapper>
        <Card className="w-full max-w-sm">
          <CardContent className="flex flex-col items-center gap-4 p-8">
            <Loader2 className="size-10 text-primary animate-spin" />
            <p className="text-sm text-muted-foreground">{t("session.magicLinkVerifying")}</p>
            {error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
          </CardContent>
        </Card>
      </CenteredWrapper>
    );
  }

  if (tfaRequired) {
    return (
      <CenteredWrapper>
        <Card className="w-full max-w-sm">
          <CardContent className="flex flex-col items-center gap-6 p-8">
            <ShieldCheck className="size-10 text-primary" />
            <div className="text-center">
              <h2 className="text-lg font-semibold">{t("session.twoFactorRequired")}</h2>
              <p className="text-sm text-muted-foreground mt-1">{t("session.twoFactorHint")}</p>
            </div>
            {error && <Alert variant="destructive" className="w-full"><AlertDescription>{error}</AlertDescription></Alert>}
            <Input
              type="text" inputMode="numeric" maxLength={6} placeholder="000000"
              className="text-center text-2xl tracking-[0.5em] font-mono"
              value={otpCode} onChange={(e) => setOtpCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
              onKeyDown={(e) => { if (e.key === "Enter") handleOtpSubmit(); }}
              autoFocus disabled={loading}
            />
            <div className="flex gap-2 w-full">
              <Button variant="outline" className="flex-1" onClick={cancelTfa} disabled={loading}>{t("common.cancel")}</Button>
              <Button className="flex-1" onClick={handleOtpSubmit} disabled={loading || otpCode.length !== 6}>
                {loading && <Loader2 className="mr-2 size-4 animate-spin" />}
                {t("session.submit")}
              </Button>
            </div>
          </CardContent>
        </Card>
      </CenteredWrapper>
    );
  }

  if (magicLinkSent) {
    return (
      <CenteredWrapper>
        <Card className="w-full max-w-sm">
          <CardContent className="flex flex-col items-center gap-4 p-8">
            <MailCheck className="size-10 text-primary" />
            <h2 className="text-lg font-semibold">{t("session.magicLinkSent")}</h2>
            <p className="text-sm text-muted-foreground text-center">{t("session.magicLinkSentHint")}</p>
            <Button variant="outline" onClick={() => switchMode("login")}>{t("session.backToLogin")}</Button>
          </CardContent>
        </Card>
      </CenteredWrapper>
    );
  }

  // --- Main form (login-04 layout: card with form + cover image) ---
  return (
    <CenteredWrapper>
      <div className="flex flex-col gap-6 w-full max-w-sm md:max-w-4xl">
        <Card className="overflow-hidden p-0">
          <CardContent className="grid p-0 md:grid-cols-2">
            {/* Left: form */}
            <form
              className="p-6 md:p-8"
              onSubmit={mode === "login" ? handleLoginSubmit : mode === "register" ? handleRegisterSubmit : handleMagicLinkSubmit}
            >
              <FieldGroup>
                <div className="flex flex-col items-center gap-2 text-center">
                  <h1 className="text-2xl font-bold">
                    {mode === "login" && t("session.loginTitle")}
                    {mode === "register" && t("session.registerTitle")}
                    {mode === "magic-link" && t("session.magicLinkTitle")}
                  </h1>
                  <p className="text-balance text-sm text-muted-foreground">
                    {mode === "login" && t("session.description")}
                    {mode === "register" && t("session.description")}
                    {mode === "magic-link" && t("session.magicLinkDesc")}
                  </p>
                </div>

                {error && (
                  <Alert variant="destructive">
                    <AlertDescription>{error}</AlertDescription>
                  </Alert>
                )}

                {/* Email */}
                <Field>
                  <FieldLabel htmlFor="email">{t("session.email")}</FieldLabel>
                  <Input
                    id="email" type="email" placeholder={t("session.emailPlaceholder")}
                    value={email} onChange={(e) => setEmail(e.target.value)}
                    disabled={loading} autoFocus required
                  />
                </Field>

                {/* Password (not for magic-link) */}
                {mode !== "magic-link" && (
                  <Field>
                    <FieldLabel htmlFor="password">{t("session.password")}</FieldLabel>
                    <Input
                      id="password" type="password" placeholder={t("session.passwordPlaceholder")}
                      value={password} onChange={(e) => setPassword(e.target.value)}
                      disabled={loading} required
                    />
                  </Field>
                )}

                {/* Confirm password (register only) */}
                {mode === "register" && (
                  <Field>
                    <FieldLabel htmlFor="confirmPassword">{t("session.confirmPassword")}</FieldLabel>
                    <Input
                      id="confirmPassword" type="password" placeholder={t("session.confirmPasswordPlaceholder")}
                      value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)}
                      disabled={loading} required
                    />
                  </Field>
                )}

                {/* Submit */}
                <Field>
                  <Button type="submit" disabled={loading} className="w-full">
                    {loading && <Loader2 className="mr-2 size-4 animate-spin" />}
                    {mode === "login" && t("session.submit")}
                    {mode === "register" && t("session.registerSubmit")}
                    {mode === "magic-link" && t("session.sendMagicLink")}
                  </Button>
                </Field>

                {/* Magic link toggle */}
                {mode === "login" && magicLinkEnabled && (
                  <>
                    <FieldSeparator className="*:data-[slot=field-separator-content]:bg-card">
                      {t("session.useMagicLink")}
                    </FieldSeparator>
                    <Field>
                      <Button type="button" variant="outline" className="w-full" onClick={() => switchMode("magic-link")}>
                        <MailCheck className="mr-2 size-4" />
                        Magic Link
                      </Button>
                    </Field>
                  </>
                )}

                {/* Mode switch links */}
                <FieldDescription className="text-center">
                  {mode === "login" && registerEnabled && (
                    <>
                      {t("session.noAccount")}{" "}
                      <button type="button" className="underline underline-offset-4 hover:text-primary" onClick={() => switchMode("register")}>
                        {t("session.registerLink")}
                      </button>
                    </>
                  )}
                  {mode === "register" && (
                    <>
                      {t("session.hasAccount")}{" "}
                      <button type="button" className="underline underline-offset-4 hover:text-primary" onClick={() => switchMode("login")}>
                        {t("session.loginLink")}
                      </button>
                    </>
                  )}
                  {mode === "magic-link" && (
                    <button type="button" className="underline underline-offset-4 hover:text-primary" onClick={() => switchMode("login")}>
                      {t("session.backToLogin")}
                    </button>
                  )}
                </FieldDescription>
              </FieldGroup>
            </form>

            {/* Right: cover image / branding */}
            <div className="relative hidden bg-muted md:flex md:flex-col md:items-center md:justify-center md:gap-4 md:p-8">
              <HardDrive className="size-16 text-muted-foreground/50" />
              <div className="text-center">
                <h2 className="text-xl font-semibold text-muted-foreground/80">DiskNext</h2>
                <p className="text-sm text-muted-foreground/60 mt-1">Your personal cloud storage</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Footer: agreement + language */}
        <div className="flex flex-col items-center gap-2">
          {showAgreement && (
            <p className="px-6 text-center text-xs text-muted-foreground">
              {t("session.agreementText")}{" "}
              {siteConfig?.tos_url && (
                <a href={siteConfig.tos_url} target="_blank" rel="noreferrer" className="underline underline-offset-4 hover:text-primary">
                  {t("session.termsOfService")}
                </a>
              )}
              {siteConfig?.tos_url && siteConfig?.privacy_url && ` ${t("session.and")} `}
              {siteConfig?.privacy_url && (
                <a href={siteConfig.privacy_url} target="_blank" rel="noreferrer" className="underline underline-offset-4 hover:text-primary">
                  {t("session.privacyPolicy")}
                </a>
              )}
            </p>
          )}
          <div className="flex items-center gap-1">
            <Languages className="size-3.5 text-muted-foreground" />
            <DropdownMenu>
              <DropdownMenuTrigger className="text-xs text-muted-foreground hover:text-foreground cursor-pointer">
                {locales.find((l) => l.code === i18n.language)?.name ?? "Language"}
              </DropdownMenuTrigger>
              <DropdownMenuContent align="center">
                {locales.map((l) => (
                  <DropdownMenuItem key={l.code} onClick={() => setLocale(l.code)}>{l.name}</DropdownMenuItem>
                ))}
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </div>
    </CenteredWrapper>
  );
}

function CenteredWrapper({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-svh flex-col items-center justify-center bg-muted p-6 md:p-10">
      {children}
    </div>
  );
}

// src/pages/session.vue
<script setup lang="ts">
import * as z from 'zod'
import type { FormSubmitEvent, AuthFormField } from '@nuxt/ui'
import { useI18n } from 'vue-i18n'
import { setLocale } from '../i18n'
import api from '../utils/api'
import { useAuthStore } from '../stores/auth'
import { useSiteConfigStore } from '../stores/siteConfig'
import { getApiErrorMessage } from '../utils/apiErrors'

const router = useRouter()
const route = useRoute()
const auth = useAuthStore()
const siteConfig = useSiteConfigStore()
const { t, locale } = useI18n()
const toast = useToast()

const supportedLocales = [
  { code: 'zh-CN', name: '简体中文' },
  { code: 'en', name: 'English' },
  { code: 'zh-TW', name: '繁體中文' },
]

function onLocaleChange(code: string) {
  setLocale(code)
}

// ---------- Agreement ----------
const showAgreement = computed(() => !!siteConfig.tosUrl || !!siteConfig.privacyUrl)

// ---------- Mode ----------
type AuthMode = 'login' | 'register' | 'magic-link'
const mode = ref<AuthMode>('login')

// ---------- Login Fields ----------
const loginFields = computed<AuthFormField[]>(() => [
  {
    name: 'email',
    type: 'text',
    label: t('session.email'),
    placeholder: t('session.emailPlaceholder'),
    required: true
  },
  {
    name: 'password',
    label: t('session.password'),
    type: 'password',
    placeholder: t('session.passwordPlaceholder'),
    required: true
  }
])

const loginSchema = computed(() => z.object({
  email: z.string({ message: t('session.emailRequired') }).min(1, t('session.emailRequired')).email(t('session.emailInvalid')),
  password: z.string({ message: t('session.passwordRequired') }).min(1, t('session.passwordRequired'))
}))

type LoginSchema = z.output<z.ZodObject<{ email: z.ZodString; password: z.ZodString }>>

// ---------- Register Fields ----------
const registerFields = computed<AuthFormField[]>(() => [
  {
    name: 'email',
    type: 'text',
    label: t('session.email'),
    placeholder: t('session.emailPlaceholder'),
    required: true
  },
  {
    name: 'password',
    label: t('session.password'),
    type: 'password',
    placeholder: t('session.passwordPlaceholder'),
    required: true
  },
  {
    name: 'confirmPassword',
    label: t('session.confirmPassword'),
    type: 'password',
    placeholder: t('session.confirmPasswordPlaceholder'),
    required: true
  },
  {
    name: 'nickname',
    type: 'text',
    label: t('session.nickname'),
    placeholder: t('session.nicknamePlaceholder')
  }
])

const registerSchema = computed(() => z.object({
  email: z.string({ message: t('session.emailRequired') }).min(1, t('session.emailRequired')).email(t('session.emailInvalid')),
  password: z.string({ message: t('session.passwordRequired') }).min(1, t('session.passwordRequired')).min(8, t('session.passwordMinLength')),
  confirmPassword: z.string({ message: t('session.confirmPasswordRequired') }).min(1, t('session.confirmPasswordRequired')),
  nickname: z.string().optional()
}).refine(data => data.password === data.confirmPassword, {
  message: t('session.passwordMismatch'),
  path: ['confirmPassword']
}))

type RegisterSchema = { email: string; password: string; confirmPassword: string; nickname?: string }

// ---------- Magic Link Fields ----------
const magicLinkFields = computed<AuthFormField[]>(() => [
  {
    name: 'email',
    type: 'text',
    label: t('session.email'),
    placeholder: t('session.emailPlaceholder'),
    required: true
  }
])

const magicLinkSchema = computed(() => z.object({
  email: z.string({ message: t('session.emailRequired') }).min(1, t('session.emailRequired')).email(t('session.emailInvalid'))
}))

type MagicLinkSchema = z.output<z.ZodObject<{ email: z.ZodString }>>

// ---------- Shared State ----------
const loading = ref(false)
const error = ref('')
const captchaCode = ref('')
const tfaRequired = ref(false)
const otpCode = ref<number[]>([])
const pendingCredentials = ref<{ email: string; password: string } | null>(null)
const captchaContainerRef = ref<HTMLDivElement>()
const captchaLoaded = ref(false)
const magicLinkSent = ref(false)
const magicLinkVerifying = ref(false)
let captchaWidgetId: number | string | null | undefined

// ---------- Captcha need ----------
const needCaptcha = computed(() => {
  if (mode.value === 'login') return siteConfig.loginCaptcha
  if (mode.value === 'register') return siteConfig.regCaptcha
  return false
})

// Load site config on mount
siteConfig.fetchConfig()

function loadScript(src: string): Promise<void> {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) {
      resolve()
      return
    }
    const script = document.createElement('script')
    script.src = src
    script.async = true
    script.onload = () => resolve()
    script.onerror = () => reject(new Error(`Failed to load script: ${src}`))
    document.head.appendChild(script)
  })
}

function renderCaptchaWidget() {
  const key = siteConfig.captchaKey
  if (!captchaContainerRef.value || !key) return

  captchaContainerRef.value.innerHTML = ''

  if (siteConfig.captchaType === 'gcaptcha') {
    captchaWidgetId = grecaptcha.render(captchaContainerRef.value, {
      sitekey: key,
      callback: (token: string) => { captchaCode.value = token },
      'expired-callback': () => { captchaCode.value = '' },
    })
  } else if (siteConfig.captchaType === 'cloudflare turnstile') {
    captchaWidgetId = turnstile.render(captchaContainerRef.value, {
      sitekey: key,
      callback: (token: string) => { captchaCode.value = token },
      'expired-callback': () => { captchaCode.value = '' },
    })
  }
}

function resetCaptcha() {
  captchaCode.value = ''
  if (captchaWidgetId === undefined) return

  if (siteConfig.captchaType === 'gcaptcha') {
    grecaptcha.reset(captchaWidgetId as number)
  } else if (siteConfig.captchaType === 'cloudflare turnstile') {
    turnstile.reset(captchaWidgetId as string)
  }
}

async function initCaptcha() {
  if (!needCaptcha.value || !siteConfig.captchaKey) return
  if (siteConfig.captchaType === 'default') return

  try {
    if (siteConfig.captchaType === 'gcaptcha') {
      await loadScript('https://www.google.com/recaptcha/api.js?render=explicit')
      await new Promise<void>((resolve) => {
        if (typeof grecaptcha !== 'undefined') {
          resolve()
        } else {
          const check = setInterval(() => {
            if (typeof grecaptcha !== 'undefined') {
              clearInterval(check)
              resolve()
            }
          }, 100)
        }
      })
    } else if (siteConfig.captchaType === 'cloudflare turnstile') {
      await loadScript('https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit')
      await new Promise<void>((resolve) => {
        if (typeof turnstile !== 'undefined') {
          resolve()
        } else {
          const check = setInterval(() => {
            if (typeof turnstile !== 'undefined') {
              clearInterval(check)
              resolve()
            }
          }, 100)
        }
      })
    }

    captchaLoaded.value = true
    nextTick(() => renderCaptchaWidget())
  } catch {
    // script load failed — allow login without captcha
  }
}

// Re-render captcha when mode changes
watch(mode, () => {
  error.value = ''
  magicLinkSent.value = false
  if (needCaptcha.value && captchaLoaded.value) {
    nextTick(() => renderCaptchaWidget())
  }
})

onMounted(async () => {
  // Handle magic link callback
  const magicToken = route.query.magic_token as string | undefined
  if (magicToken) {
    magicLinkVerifying.value = true
   try {
      const { data } = await api.post('/api/v1/user/session', {
        provider: 'magic_link',
        identifier: magicToken
      })
      auth.setSession(data)
      router.push('/home')
      return
    } catch (e: unknown) {
      error.value = getApiErrorMessage(e, t('session.magicLinkLoginFailed'), {
        410: t('session.magicLinkInvalidToken'),
        400: t('errors.invalidParams')
      })
    } finally {
      magicLinkVerifying.value = false
    }
  }

  watch(
    () => siteConfig.fetched,
    (fetched) => {
      if (fetched) initCaptcha()
    },
    { immediate: true }
  )
})

// ---------- Login ----------
async function submitLogin(email: string, password: string, otp?: string) {
  loading.value = true
  error.value = ''

  try {
    const body: Record<string, string> = {
      provider: 'email_password',
      identifier: email,
      credential: password,
    }

    if (otp) {
      body.two_fa_code = otp
    }

    if (needCaptcha.value && captchaCode.value) {
      body.captcha = captchaCode.value
    }

    const { data } = await api.post('/api/v1/user/session', body)

    auth.setSession(data)
    router.push('/home')
  } catch (e: unknown) {
    const err = e as { response?: { status?: number } }

    if (err.response?.status === 428) {
      pendingCredentials.value = { email, password }
      tfaRequired.value = true
      otpCode.value = []
      error.value = ''
      return
    }

    if (err.response?.status === 403) {
      error.value = t('session.accountBanned')
    } else if (err.response?.status) {
      error.value = getApiErrorMessage(e, t('errors.loginFailed'), {
        403: t('session.accountBanned'),
        400: t('errors.invalidParams'),
      })
    } else {
      error.value = getApiErrorMessage(e, t('errors.loginFailedCheck'))
    }

    if (tfaRequired.value) {
      otpCode.value = []
    } else {
      resetCaptcha()
    }
  } finally {
    loading.value = false
  }
}

async function onLoginSubmit(payload: FormSubmitEvent<LoginSchema>) {
  if (needCaptcha.value && siteConfig.captchaType !== 'default') {
    if (!captchaCode.value) {
      error.value = t('session.captchaRequired')
      return
    }
  }

  await submitLogin(payload.data.email, payload.data.password)
}

// ---------- Register ----------
async function onRegisterSubmit(payload: FormSubmitEvent<RegisterSchema>) {
  if (needCaptcha.value && siteConfig.captchaType !== 'default') {
    if (!captchaCode.value) {
      error.value = t('session.captchaRequired')
      return
    }
  }

  loading.value = true
  error.value = ''

  try {
    const body: Record<string, unknown> = {
      provider: 'email_password',
      identifier: payload.data.email,
      credential: payload.data.password
    }

    if (payload.data.nickname) {
      body.nickname = payload.data.nickname
    }

    if (needCaptcha.value && captchaCode.value) {
      body.captcha = captchaCode.value
    }

    await api.post('/api/v1/user', body)

    toast.add({ title: t('session.registerSuccess'), color: 'success' })

    // Auto-login after successful registration
    try {
      await submitLogin(payload.data.email, payload.data.password)
    } catch {
      mode.value = 'login'
    }
  } catch (e: unknown) {
    error.value = getApiErrorMessage(e, t('session.registerFailed'), {
      409: t('errors.conflict'),
      400: t('errors.invalidParams')
    })
    resetCaptcha()
  } finally {
    loading.value = false
  }
}

// ---------- Magic Link ----------
async function onMagicLinkSubmit(payload: FormSubmitEvent<MagicLinkSchema>) {
  loading.value = true
  error.value = ''

  try {
    await api.post('/api/v1/user/magic-link', {
      email: payload.data.email
    })
    magicLinkSent.value = true
  } catch (e: unknown) {
    error.value = getApiErrorMessage(e, t('errors.loginFailed'), {
      400: t('errors.invalidParams'),
      429: t('errors.fetchFailed')
    })
  } finally {
    loading.value = false
  }
}

// ---------- 2FA ----------
function onOtpComplete() {
  if (!pendingCredentials.value) return
  const code = otpCode.value.join('')
  if (code.length !== 6) return
  submitLogin(pendingCredentials.value.email, pendingCredentials.value.password, code)
}

function cancelTfa() {
  tfaRequired.value = false
  pendingCredentials.value = null
  otpCode.value = []
  error.value = ''
}
</script>

<template>
  <div class="flex flex-col items-center justify-center min-h-svh p-4">
    <UPageCard class="w-full max-w-md">
      <!-- Magic Link Verifying -->
      <div
        v-if="magicLinkVerifying"
        class="flex flex-col items-center gap-4 p-6"
      >
        <UIcon
          name="i-lucide-loader-circle"
          class="size-10 text-primary animate-spin"
        />
        <p class="text-sm text-muted">
          {{ t('session.magicLinkVerifying') }}
        </p>
        <UAlert
          v-if="error"
          color="error"
          icon="i-lucide-circle-x"
          :title="error"
          class="w-full"
        />
      </div>

      <!-- 2FA OTP Input -->
      <div
        v-else-if="tfaRequired"
        class="flex flex-col items-center gap-6 p-6"
      >
        <UIcon
          name="i-lucide-shield-check"
          class="size-10 text-primary"
        />
        <div class="text-center">
          <h2 class="text-lg font-semibold">
            {{ t('session.twoFactorRequired') }}
          </h2>
          <p class="text-sm text-muted mt-1">
            {{ t('session.twoFactorHint') }}
          </p>
        </div>

        <UAlert
          v-if="error"
          color="error"
          icon="i-lucide-circle-x"
          :title="error"
          class="w-full"
        />

        <UPinInput
          v-model="otpCode"
          :length="6"
          type="number"
          otp
          autofocus
          :disabled="loading"
          @complete="onOtpComplete"
        />

        <div class="flex gap-2 w-full">
          <UButton
            :label="t('common.cancel')"
            color="neutral"
            variant="outline"
            block
            :disabled="loading"
            @click="cancelTfa"
          />
          <UButton
            :label="t('session.submit')"
            block
            :loading="loading"
            :disabled="otpCode.length !== 6 || otpCode.some(c => c === undefined || c === null)"
            @click="onOtpComplete"
          />
        </div>
      </div>

      <!-- Magic Link Sent -->
      <div
        v-else-if="magicLinkSent"
        class="flex flex-col items-center gap-4 p-6"
      >
        <UIcon
          name="i-lucide-mail-check"
          class="size-10 text-primary"
        />
        <div class="text-center">
          <h2 class="text-lg font-semibold">
            {{ t('session.magicLinkSent') }}
          </h2>
          <p class="text-sm text-muted mt-2">
            {{ t('session.magicLinkSentHint') }}
          </p>
        </div>
        <UButton
          :label="t('session.backToLogin')"
          color="neutral"
          variant="outline"
          @click="magicLinkSent = false; mode = 'login'"
        />
      </div>

      <!-- Login Form -->
      <UAuthForm
        v-else-if="mode === 'login'"
        :schema="loginSchema"
        :fields="loginFields"
        :loading="loading"
        :title="t('session.loginTitle')"
        :description="t('session.description')"
        icon="i-lucide-hard-drive"
        :submit="{ label: t('session.submit'), block: true }"
        :providers="[]"
        @submit="onLoginSubmit"
      >
        <template
          v-if="error"
          #validation
        >
          <UAlert
            color="error"
            icon="i-lucide-circle-x"
            :title="error"
          />
        </template>

        <template #description>
          <p class="text-sm text-muted">
            {{ t('session.description') }}
          </p>
          <p
            v-if="siteConfig.registerEnabled && siteConfig.isProviderEnabled('email_password')"
            class="text-sm mt-1"
          >
            {{ t('session.noAccount') }}
            <UButton
              variant="link"
              :label="t('session.registerLink')"
              class="p-0"
              @click="mode = 'register'"
            />
          </p>
        </template>

        <template #footer>
          <div class="flex flex-col gap-3">
            <div
              v-if="needCaptcha && siteConfig.captchaType !== 'default'"
              class="flex justify-center"
            >
              <div
                v-if="captchaLoaded"
                ref="captchaContainerRef"
              />
              <p
                v-else
                class="text-sm text-muted"
              >
                {{ t('session.captchaLoading') }}
              </p>
            </div>
            <div
              v-if="siteConfig.isProviderEnabled('magic_link')"
              class="text-center"
            >
              <UButton
                variant="link"
                :label="t('session.useMagicLink')"
                @click="mode = 'magic-link'"
              />
            </div>
            <p
              v-if="showAgreement"
              class="text-xs text-center text-muted"
            >
              {{ t('session.agreementText') }}
              <ULink
                v-if="siteConfig.tosUrl"
                :to="siteConfig.tosUrl"
                target="_blank"
                class="text-primary font-medium"
              >
                {{ t('session.termsOfService') }}
              </ULink>
              <template v-if="siteConfig.tosUrl && siteConfig.privacyUrl">
                {{ t('session.and') }}
              </template>
              <ULink
                v-if="siteConfig.privacyUrl"
                :to="siteConfig.privacyUrl"
                target="_blank"
                class="text-primary font-medium"
              >
                {{ t('session.privacyPolicy') }}
              </ULink>
            </p>
          </div>
        </template>
      </UAuthForm>

      <!-- Register Form -->
      <UAuthForm
        v-else-if="mode === 'register'"
        :schema="registerSchema"
        :fields="registerFields"
        :loading="loading"
        :title="t('session.registerTitle')"
        icon="i-lucide-hard-drive"
        :submit="{ label: t('session.registerSubmit'), block: true }"
        @submit="onRegisterSubmit"
      >
        <template
          v-if="error"
          #validation
        >
          <UAlert
            color="error"
            icon="i-lucide-circle-x"
            :title="error"
          />
        </template>

        <template #description>
          <p class="text-sm">
            {{ t('session.hasAccount') }}
            <UButton
              variant="link"
              :label="t('session.loginLink')"
              class="p-0"
              @click="mode = 'login'"
            />
          </p>
        </template>

        <template #footer>
          <div class="flex flex-col gap-3">
            <div
              v-if="needCaptcha && siteConfig.captchaType !== 'default'"
              class="flex justify-center"
            >
              <div
                v-if="captchaLoaded"
                ref="captchaContainerRef"
              />
              <p
                v-else
                class="text-sm text-muted"
              >
                {{ t('session.captchaLoading') }}
              </p>
            </div>
            <p
              v-if="showAgreement"
              class="text-xs text-center text-muted"
            >
              {{ t('session.agreementText') }}
              <ULink
                v-if="siteConfig.tosUrl"
                :to="siteConfig.tosUrl"
                target="_blank"
                class="text-primary font-medium"
              >
                {{ t('session.termsOfService') }}
              </ULink>
              <template v-if="siteConfig.tosUrl && siteConfig.privacyUrl">
                {{ t('session.and') }}
              </template>
              <ULink
                v-if="siteConfig.privacyUrl"
                :to="siteConfig.privacyUrl"
                target="_blank"
                class="text-primary font-medium"
              >
                {{ t('session.privacyPolicy') }}
              </ULink>
            </p>
          </div>
        </template>
      </UAuthForm>

      <!-- Magic Link Form -->
      <UAuthForm
        v-else-if="mode === 'magic-link'"
        :schema="magicLinkSchema"
        :fields="magicLinkFields"
        :loading="loading"
        :title="t('session.magicLinkTitle')"
        :description="t('session.magicLinkDesc')"
        icon="i-lucide-mail"
        :submit="{ label: t('session.sendMagicLink'), block: true }"
        @submit="onMagicLinkSubmit"
      >
        <template
          v-if="error"
          #validation
        >
          <UAlert
            color="error"
            icon="i-lucide-circle-x"
            :title="error"
          />
        </template>

        <template #description>
          <p class="text-sm text-muted">
            {{ t('session.magicLinkDesc') }}
          </p>
          <p class="text-sm mt-1">
            <UButton
              variant="link"
              :label="t('session.backToLogin')"
              class="p-0"
              @click="mode = 'login'"
            />
          </p>
        </template>

        <template
          v-if="showAgreement"
          #footer
        >
          <p class="text-xs text-center text-muted">
            {{ t('session.agreementText') }}
            <ULink
              v-if="siteConfig.tosUrl"
              :to="siteConfig.tosUrl"
              target="_blank"
              class="text-primary font-medium"
            >
              {{ t('session.termsOfService') }}
            </ULink>
            <template v-if="siteConfig.tosUrl && siteConfig.privacyUrl">
              {{ t('session.and') }}
            </template>
            <ULink
              v-if="siteConfig.privacyUrl"
              :to="siteConfig.privacyUrl"
              target="_blank"
              class="text-primary font-medium"
            >
              {{ t('session.privacyPolicy') }}
            </ULink>
          </p>
        </template>
      </UAuthForm>

      <div class="flex justify-center mt-4">
        <div class="flex items-center gap-1">
          <UIcon
            name="i-lucide-languages"
            class="size-4 text-muted"
          />
          <UDropdownMenu
            :items="[[
              ...supportedLocales.map(l => ({
                label: l.name,
                active: locale === l.code,
                onSelect() { onLocaleChange(l.code) }
              }))
            ]]"
            :content="{ align: 'center' as const }"
          >
            <UButton
              size="sm"
              color="neutral"
              variant="ghost"
              :label="supportedLocales.find(l => l.code === locale)?.name"
              trailing-icon="i-lucide-chevron-down"
            />
          </UDropdownMenu>
        </div>
      </div>
    </UPageCard>
  </div>
</template>
