// src/pages/shares.vue
<script setup lang="ts">
import { h, resolveComponent } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { setLocale } from '../i18n'
import type { DropdownMenuItem, TableColumn } from '@nuxt/ui'
import type { AxiosError } from 'axios'
import { useAdminStore } from '../stores/admin'
import { useUserStore } from '../stores/user'
import { useAuthStore } from '../stores/auth'
import api from '../utils/api'

const UBadge = resolveComponent('UBadge')
const UIcon = resolveComponent('UIcon')
const UTooltip = resolveComponent('UTooltip')
const UDropdownMenu = resolveComponent('UDropdownMenu')
const UButton = resolveComponent('UButton')

const router = useRouter()
const toast = useToast()
const admin = useAdminStore()
const user = useUserStore()
const auth = useAuthStore()
const { t, locale } = useI18n()

interface ShareItem {
  id: string
  code: string
  object_id: string
  source_name: string | null
  views: number
  downloads: number
  remain_downloads: number | null
  expires: string | null
  preview_enabled: boolean
  score: number
  created_at: string
  is_expired: boolean
  has_password: boolean
}

interface ShareListResponse {
  count: number
  items: ShareItem[]
}

const shares = ref<ShareItem[]>([])
const total = ref(0)
const loading = ref(true)
const page = ref(1)
const pageSize = 20
const orderBy = ref('created_at')
const orderDesc = ref(true)
const searchQuery = ref('')
const debouncedSearch = ref('')
const filterExpired = ref('')

const deleteModalOpen = ref(false)
const deletingShare = ref<ShareItem | null>(null)
const deleting = ref(false)

let debounceTimer: ReturnType<typeof setTimeout> | null = null

watch(searchQuery, (val) => {
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => {
    debouncedSearch.value = val
    page.value = 1
  }, 300)
})

watch([page, orderDesc, debouncedSearch, filterExpired], () => {
  fetchShares()
})

async function fetchShares() {
  loading.value = true
  try {
    const params: Record<string, unknown> = {
      offset: (page.value - 1) * pageSize,
      limit: pageSize,
      order: orderBy.value,
      desc: orderDesc.value,
    }
    if (debouncedSearch.value) params.keyword = debouncedSearch.value
    if (filterExpired.value) params.expired = filterExpired.value === 'true'
    const { data } = await api.get<ShareListResponse>('/api/v1/share/', { params })
    shares.value = data.items
    total.value = data.count
  } catch (e: unknown) {
    const err = e as AxiosError<{ detail?: string }>
    const message = err?.response?.data?.detail || t('myShares.loadFailed')
    toast.add({
      title: t('myShares.loadFailed'),
      description: message,
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
  } finally {
    loading.value = false
  }
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString(locale.value, {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

function copyLink(item: ShareItem) {
  const link = `${window.location.origin}/s/${item.code}`
  navigator.clipboard.writeText(link)
  toast.add({ title: t('myShares.copied'), icon: 'i-lucide-check-circle', color: 'success' })
}

function openDeleteModal(item: ShareItem) {
  deletingShare.value = item
  deleteModalOpen.value = true
}

async function confirmDelete() {
  if (!deletingShare.value) return
  deleting.value = true
  try {
    await api.delete(`/api/v1/share/${deletingShare.value.id}`)
    toast.add({ title: t('myShares.deleteSuccess'), icon: 'i-lucide-check-circle', color: 'success' })
    deleteModalOpen.value = false
    fetchShares()
  } catch (e: unknown) {
    const err = e as AxiosError<{ detail?: string }>
    toast.add({
      title: t('myShares.deleteFailed'),
      description: err.response?.data?.detail || '',
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
  } finally {
    deleting.value = false
  }
}

const expiredFilterItems = [
  { label: t('myShares.filterActive'), value: 'false' },
  { label: t('myShares.filterExpired'), value: 'true' },
]

const columns = computed<TableColumn<ShareItem>[]>(() => [
  {
    accessorKey: 'source_name',
    header: t('myShares.sourceName'),
    cell: ({ row }) => {
      const name = row.original.source_name || '-'
      return h(UTooltip, { text: name }, {
        default: () => h('span', { class: 'truncate max-w-48 inline-block align-bottom' }, name)
      })
    }
  },
  {
    accessorKey: 'is_expired',
    header: t('myShares.status'),
    cell: ({ row }) => {
      const badges = []
      badges.push(h(UBadge, {
        label: row.original.is_expired ? t('myShares.expired') : t('myShares.active'),
        color: row.original.is_expired ? 'error' : 'success',
        variant: 'subtle',
        size: 'sm'
      }))
      if (row.original.has_password) {
        badges.push(h(UIcon, { name: 'i-lucide-lock', class: 'size-4 text-muted ml-1' }))
      }
      return h('div', { class: 'flex items-center' }, badges)
    }
  },
  {
    accessorKey: 'views',
    header: t('myShares.viewsDownloads'),
    cell: ({ row }) => `${row.original.views} / ${row.original.downloads}`,
    meta: { class: { td: 'text-muted' } }
  },
  {
    accessorKey: 'remain_downloads',
    header: t('myShares.downloadLimit'),
    cell: ({ row }) => row.original.remain_downloads != null
      ? String(row.original.remain_downloads)
      : t('myShares.unlimited'),
    meta: { class: { td: 'text-muted' } }
  },
  {
    accessorKey: 'expires',
    header: t('myShares.expires'),
    cell: ({ row }) => row.original.expires
      ? formatDate(row.original.expires)
      : t('myShares.neverExpire'),
    meta: { class: { td: 'text-muted' } }
  },
  {
    accessorKey: 'created_at',
    header: t('myShares.createdAt'),
    cell: ({ row }) => formatDate(row.original.created_at),
    meta: { class: { td: 'text-muted' } }
  },
  {
    id: 'actions',
    header: t('myShares.actions'),
    cell: ({ row }) => {
      const items: DropdownMenuItem[][] = [
        [
          {
            label: t('myShares.copyLink'),
            icon: 'i-lucide-copy',
            onSelect() { copyLink(row.original) }
          }
        ],
        [
          {
            label: t('myShares.deleteShare'),
            icon: 'i-lucide-trash-2',
            color: 'error' as const,
            onSelect() { openDeleteModal(row.original) }
          }
        ]
      ]
      return h(UDropdownMenu, { items }, {
        default: () => h(UButton, {
          icon: 'i-lucide-ellipsis-vertical',
          color: 'neutral',
          variant: 'ghost',
          size: 'xs'
        })
      })
    }
  }
])

onMounted(() => {
  admin.checkAdmin()
  fetchShares()
})

const userMenuItems = computed<DropdownMenuItem[][]>(() => {
  const header: DropdownMenuItem[] = [
    {
      label: `${user.nickname}${admin.isAdmin ? ' ' + t('user.admin') : ''}`,
      description: user.email,
      type: 'label'
    }
  ]

  const actions: DropdownMenuItem[] = []
  if (admin.isAdmin) {
    actions.push({
      label: t('user.adminPanel'),
      icon: 'i-lucide-shield',
      onSelect() {
        router.push('/admin')
      }
    })
  }
  actions.push({
    label: t('user.settingsAndAbout'),
    icon: 'i-lucide-settings',
    onSelect() {
      router.push('/settings')
    }
  })
  actions.push({
    label: t('user.language'),
    icon: 'i-lucide-languages',
    children: [
      { label: '简体中文', onSelect() { setLocale('zh-CN') } },
      { label: 'English', onSelect() { setLocale('en') } },
      { label: '繁體中文', onSelect() { setLocale('zh-TW') } }
    ]
  })

  const logout: DropdownMenuItem[] = [
    {
      label: t('user.logout'),
      icon: 'i-lucide-log-out',
      color: 'error',
      onSelect() {
        auth.logout()
        user.clear()
        router.push('/session')
      }
    }
  ]

  return [header, actions, logout]
})
</script>

<template>
  <UDashboardGroup>
    <AppSidebar />

    <UDashboardPanel>
      <template #header>
        <UDashboardNavbar>
          <template #leading>
            <UDashboardSidebarCollapse />
            <span class="text-sm font-semibold">{{ t('myShares.title') }}</span>
          </template>

          <template #right>
            <UColorModeButton />
            <UDropdownMenu
              :items="userMenuItems"
              :content="{ align: 'end' }"
            >
              <UAvatar
                :alt="user.nickname"
                size="sm"
              />
            </UDropdownMenu>
          </template>
        </UDashboardNavbar>
      </template>

      <template #body>
        <div class="p-6 space-y-6">
          <div class="flex items-center gap-3">
            <UInput
              v-model="searchQuery"
              :placeholder="t('myShares.searchPlaceholder')"
              icon="i-lucide-search"
              class="w-64"
            />
            <USelectMenu
              v-model="filterExpired"
              :items="expiredFilterItems"
              value-key="value"
              :placeholder="t('myShares.allStatus')"
              :search-input="false"
              clear
              class="w-36"
            />
            <div class="flex-1" />
            <UButton
              :icon="orderDesc ? 'i-lucide-arrow-down-wide-narrow' : 'i-lucide-arrow-up-wide-narrow'"
              color="neutral"
              variant="ghost"
              @click="orderDesc = !orderDesc"
            />
            <UButton
              icon="i-lucide-refresh-cw"
              color="neutral"
              variant="ghost"
              @click="fetchShares"
            />
          </div>

          <div
            v-if="loading"
            class="flex justify-center py-12"
          >
            <UIcon
              name="i-lucide-loader-2"
              class="size-8 animate-spin text-muted"
            />
          </div>

          <div
            v-else-if="shares.length === 0"
            class="text-center py-12 text-muted"
          >
            <UIcon
              name="i-lucide-share-2"
              class="size-12 mx-auto mb-4 opacity-50"
            />
            <p>{{ t('myShares.empty') }}</p>
          </div>

          <template v-else>
            <UTable
              :data="shares"
              :columns="columns"
            />
            <div
              v-if="total > pageSize"
              class="flex justify-center"
            >
              <UPagination
                v-model:page="page"
                :total="total"
                :items-per-page="pageSize"
                show-edges
              />
            </div>
          </template>
        </div>
      </template>
    </UDashboardPanel>
    <UModal
      v-model:open="deleteModalOpen"
      :title="t('myShares.deleteShare')"
      description=" "
      :ui="{ footer: 'justify-end', description: 'hidden' }"
    >
      <template #body>
        <p class="text-sm">
          {{ t('myShares.deleteConfirm', { name: deletingShare?.source_name || deletingShare?.code }) }}
        </p>
      </template>

      <template #footer>
        <UButton
          :label="t('common.cancel')"
          color="neutral"
          variant="outline"
          @click="deleteModalOpen = false"
        />
        <UButton
          :label="t('common.delete')"
          color="error"
          :loading="deleting"
          @click="confirmDelete"
        />
      </template>
    </UModal>
  </UDashboardGroup>
</template>

// src/pages/shares.tsx
import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter,
  DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { Copy, Trash2, Link2, Loader2, ChevronLeft, ChevronRight } from "lucide-react";
import { share, resolveErrorMessage, ApiError } from "@/api";
import type { ShareResponse } from "@/api";

const PAGE_SIZE = 20;

type FilterTab = "all" | "active" | "expired";

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    year: "numeric", month: "2-digit", day: "2-digit",
    hour: "2-digit", minute: "2-digit",
  });
}

export default function SharesPage() {
  const { t } = useTranslation();
  const [items, setItems] = useState<ShareResponse[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(0);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<FilterTab>("all");

  // Delete dialog
  const [deleteTarget, setDeleteTarget] = useState<ShareResponse | null>(null);
  const [deleting, setDeleting] = useState(false);

  const loadShares = useCallback(async () => {
    setLoading(true);
    try {
      const expired = filter === "all" ? undefined : filter === "expired";
      const data = await share.list({
        offset: page * PAGE_SIZE,
        limit: PAGE_SIZE,
        expired,
      });
      setItems(data.items);
      setTotal(data.count);
    } catch (err) {
      const msg = err instanceof ApiError ? err.message : t("common.loading");
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  }, [page, filter, t]);

  useEffect(() => {
    loadShares();
  }, [loadShares]);

  const handleFilterChange = (value: string) => {
    setFilter(value as FilterTab);
    setPage(0);
  };

  const handleCopyLink = (code: string) => {
    const url = `${window.location.origin}/s/${code}`;
    navigator.clipboard.writeText(url).then(() => {
      toast.success(t("share.linkCopied"));
    });
  };

  const handleDelete = async () => {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      await share.delete(deleteTarget.id);
      toast.success(t("share.deleteSuccess"));
      setDeleteTarget(null);
      loadShares();
    } catch (err) {
      toast.error(resolveErrorMessage(err));
    } finally {
      setDeleting(false);
    }
  };

  const totalPages = Math.ceil(total / PAGE_SIZE);

  return (
    <div className="flex flex-1 flex-col gap-4">
      <div className="flex items-center justify-between">
        <Tabs value={filter} onValueChange={handleFilterChange}>
          <TabsList>
            <TabsTrigger value="all">{t("share.all")}</TabsTrigger>
            <TabsTrigger value="active">{t("share.active")}</TabsTrigger>
            <TabsTrigger value="expired">{t("share.expired")}</TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {loading ? (
        <div className="flex flex-col gap-3">
          {Array.from({ length: 5 }).map((_, i) => (
            <div key={i} className="flex items-center gap-3">
              <Skeleton className="h-5 flex-1" />
              <Skeleton className="h-5 w-12" />
              <Skeleton className="h-5 w-12" />
              <Skeleton className="h-5 w-20" />
              <Skeleton className="h-5 w-28" />
              <Skeleton className="h-5 w-16" />
            </div>
          ))}
        </div>
      ) : items.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <Link2 />
            </EmptyMedia>
            <EmptyTitle>{t("share.noShares")}</EmptyTitle>
            <EmptyDescription>{t("share.noSharesHint")}</EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t("file.name")}</TableHead>
                <TableHead className="w-16 text-right">{t("share.views")}</TableHead>
                <TableHead className="w-16 text-right">{t("share.downloads")}</TableHead>
                <TableHead className="w-28">{t("share.status")}</TableHead>
                <TableHead className="w-40 text-right">{t("share.createdAt")}</TableHead>
                <TableHead className="w-24 text-right">{t("share.actions")}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((item) => (
                <TableRow key={item.id}>
                  <TableCell className="font-medium">
                    <span className="truncate">{item.file_id.slice(0, 8)}…</span>
                  </TableCell>
                  <TableCell className="text-right text-muted-foreground">{item.views}</TableCell>
                  <TableCell className="text-right text-muted-foreground">{item.downloads}</TableCell>
                  <TableCell>
                    <div className="flex gap-1">
                      {item.is_expired ? (
                        <Badge variant="destructive">{t("share.expired")}</Badge>
                      ) : item.expires ? (
                        <Badge variant="secondary">{t("share.active")}</Badge>
                      ) : (
                        <Badge variant="outline">{t("share.permanent")}</Badge>
                      )}
                      {item.has_password && (
                        <Badge variant="outline">{t("share.hasPassword")}</Badge>
                      )}
                    </div>
                  </TableCell>
                  <TableCell className="text-right text-muted-foreground">
                    {formatDate(item.created_at)}
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-1">
                      <Button variant="ghost" size="icon" className="size-8" onClick={() => handleCopyLink(item.code)}>
                        <Copy className="size-4" />
                      </Button>
                      <Button variant="ghost" size="icon" className="size-8 text-destructive" onClick={() => setDeleteTarget(item)}>
                        <Trash2 className="size-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          {totalPages > 1 && (
            <div className="flex items-center justify-center gap-2">
              <Button variant="outline" size="icon" className="size-8" disabled={page === 0} onClick={() => setPage(page - 1)}>
                <ChevronLeft className="size-4" />
              </Button>
              <span className="text-sm text-muted-foreground">
                {page + 1} / {totalPages}
              </span>
              <Button variant="outline" size="icon" className="size-8" disabled={page >= totalPages - 1} onClick={() => setPage(page + 1)}>
                <ChevronRight className="size-4" />
              </Button>
            </div>
          )}
        </>
      )}

      {/* Delete confirmation dialog */}
      <Dialog open={!!deleteTarget} onOpenChange={(v) => { if (!v) setDeleteTarget(null); }}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{t("share.deleteShare")}</DialogTitle>
            <DialogDescription>{t("share.deleteConfirm")}</DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteTarget(null)} disabled={deleting}>
              {t("common.cancel")}
            </Button>
            <Button variant="destructive" onClick={handleDelete} disabled={deleting}>
              {deleting && <Loader2 className="mr-2 size-4 animate-spin" />}
              {t("common.delete")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
