// src/pages/admin/shares.vue
<script setup lang="ts">
import { h, ref, computed, onMounted, watch, resolveComponent } from 'vue'
import { useI18n } from 'vue-i18n'
import type { TableColumn, DropdownMenuItem } from '@nuxt/ui'
import type { AxiosError } from 'axios'
import api from '../../utils/api'

type ApiErrorResponse = { detail?: string }

const UBadge = resolveComponent('UBadge')
const UTooltip = resolveComponent('UTooltip')
const UDropdownMenu = resolveComponent('UDropdownMenu')

const { t, locale } = useI18n()
const toast = useToast()

interface AdminShareItem {
  id: string
  code: string
  views: number
  downloads: number
  remain_downloads: number | null
  expires: string | null
  preview_enabled: boolean
  score: number
  user_id: string
  created_at: string
  username: string | null
  object_name: string | null
}

interface AdminShareListResponse {
  count: number
  items: AdminShareItem[]
}

interface AdminShareDetail {
  id: string
  code: string
  views: number
  downloads: number
  remain_downloads: number | null
  expires: string | null
  preview_enabled: boolean
  score: number
  has_password: boolean
  user_id: string
  username: string | null
  object: Record<string, unknown>
  created_at: string
}

// List state
const shares = ref<AdminShareItem[]>([])
const total = ref(0)
const loading = ref(true)
const page = ref(1)
const pageSize = 20
const orderBy = ref('created_at')
const orderDesc = ref(true)

const orderOptions = [
  { label: t('adminShare.orderCreatedAt'), value: 'created_at' },
  { label: t('adminShare.orderUpdatedAt'), value: 'updated_at' }
]

// Delete modal
const deleteModalOpen = ref(false)
const deletingShare = ref<AdminShareItem | null>(null)
const deleting = ref(false)

// Detail modal
const detailModalOpen = ref(false)
const detailLoading = ref(false)
const shareDetail = ref<AdminShareDetail | null>(null)

function formatDate(iso: string): string {
  if (!iso) return '-'
  return new Date(iso).toLocaleString(locale.value, {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

async function fetchShares() {
  loading.value = true
  try {
    const { data } = await api.get<AdminShareListResponse>('/api/v1/admin/share/list', {
      params: {
        offset: (page.value - 1) * pageSize,
        limit: pageSize,
        order: orderBy.value,
        desc: orderDesc.value
      }
    })
    shares.value = data.items
    total.value = data.count
  } catch (e: unknown) {
    const err = e as AxiosError<ApiErrorResponse>
    toast.add({
      title: t('adminShare.loadFailed'),
      description: err.response?.data?.detail || '',
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
  } finally {
    loading.value = false
  }
}

watch(page, () => fetchShares())
watch([orderBy, orderDesc], () => {
  page.value = 1
  fetchShares()
})

onMounted(() => {
  fetchShares()
})

function copyLink(item: AdminShareItem) {
  const link = `${window.location.origin}/s/${item.code}`
  navigator.clipboard.writeText(link)
  toast.add({ title: t('adminShare.copied'), icon: 'i-lucide-check-circle', color: 'success' })
}

function openDeleteModal(item: AdminShareItem) {
  deletingShare.value = item
  deleteModalOpen.value = true
}

async function confirmDelete() {
  if (!deletingShare.value) return
  deleting.value = true
  try {
    await api.delete(`/api/v1/admin/share/${deletingShare.value.id}`)
    toast.add({ title: t('adminShare.deleteSuccess'), icon: 'i-lucide-check-circle', color: 'success' })
    deleteModalOpen.value = false
    fetchShares()
  } catch (e: unknown) {
    const err = e as AxiosError<ApiErrorResponse>
    toast.add({
      title: t('adminShare.deleteFailed'),
      description: err.response?.data?.detail || '',
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
  } finally {
    deleting.value = false
  }
}

async function openDetailModal(item: AdminShareItem) {
  shareDetail.value = null
  detailModalOpen.value = true
  detailLoading.value = true
  try {
    const { data } = await api.get<AdminShareDetail>(`/api/v1/admin/share/${item.id}`)
    shareDetail.value = data
  } catch (e: unknown) {
    const err = e as AxiosError<ApiErrorResponse>
    toast.add({
      title: t('adminShare.loadFailed'),
      description: err.response?.data?.detail || '',
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
    detailModalOpen.value = false
  } finally {
    detailLoading.value = false
  }
}

function getDropdownItems(item: AdminShareItem): DropdownMenuItem[][] {
  return [
    [
      {
        label: t('adminShare.copyLink'),
        icon: 'i-lucide-copy',
        onSelect() { copyLink(item) }
      },
      {
        label: t('adminShare.viewDetail'),
        icon: 'i-lucide-eye',
        onSelect() { openDetailModal(item) }
      }
    ],
    [
      {
        label: t('adminShare.deleteShare'),
        icon: 'i-lucide-trash-2',
        color: 'error' as const,
        onSelect() { openDeleteModal(item) }
      }
    ]
  ]
}

const columns = computed<TableColumn<AdminShareItem>[]>(() => [
  {
    accessorKey: 'object_name',
    header: t('adminShare.objectName'),
    cell: ({ row }) => {
      const name = row.original.object_name || '-'
      return h(UTooltip, { text: name }, {
        default: () => h('span', { class: 'truncate max-w-48 inline-block align-bottom' }, name)
      })
    }
  },
  {
    accessorKey: 'username',
    header: t('adminShare.username'),
    cell: ({ row }) => row.original.username || '-'
  },
  {
    accessorKey: 'views',
    header: t('adminShare.viewsDownloads'),
    cell: ({ row }) => `${row.original.views} / ${row.original.downloads}`,
    meta: { class: { td: 'text-muted' } }
  },
  {
    accessorKey: 'remain_downloads',
    header: t('adminShare.downloadLimit'),
    cell: ({ row }) => row.original.remain_downloads != null
      ? String(row.original.remain_downloads)
      : t('adminShare.unlimited'),
    meta: { class: { td: 'text-muted' } }
  },
  {
    accessorKey: 'preview_enabled',
    header: t('adminShare.preview'),
    cell: ({ row }) => h(UBadge, {
      label: row.original.preview_enabled ? t('adminShare.previewOn') : t('adminShare.previewOff'),
      color: row.original.preview_enabled ? 'success' : 'neutral',
      variant: 'subtle',
      size: 'md'
    })
  },
  {
    accessorKey: 'expires',
    header: t('adminShare.expires'),
    cell: ({ row }) => row.original.expires
      ? formatDate(row.original.expires)
      : t('adminShare.neverExpire'),
    meta: { class: { td: 'text-muted' } }
  },
  {
    accessorKey: 'created_at',
    header: t('adminShare.createdAt'),
    cell: ({ row }) => formatDate(row.original.created_at),
    meta: { class: { td: 'text-muted' } }
  },
  {
    id: 'actions',
    header: t('adminShare.actions'),
    cell: ({ row }) => {
      return h(UDropdownMenu, {
        items: getDropdownItems(row.original),
        content: { align: 'end' }
      }, {
        default: () => h(resolveComponent('UButton'), {
          icon: 'i-lucide-ellipsis-vertical',
          color: 'neutral',
          variant: 'ghost',
          size: 'xs'
        })
      })
    }
  }
])
</script>

<template>
  <div class="p-6 space-y-6">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <h1 class="text-2xl font-semibold">
        {{ t('adminShare.title') }}
      </h1>
      <div class="flex items-center gap-2">
        <USelect
          v-model="orderBy"
          :items="orderOptions"
          class="w-32"
        />
        <UButton
          :icon="orderDesc ? 'i-lucide-arrow-down-wide-narrow' : 'i-lucide-arrow-up-narrow-wide'"
          color="neutral"
          variant="ghost"
          @click="orderDesc = !orderDesc"
        />
        <UButton
          icon="i-lucide-refresh-cw"
          color="neutral"
          variant="ghost"
          @click="fetchShares"
        />
      </div>
    </div>

    <!-- Loading -->
    <div
      v-if="loading"
      class="flex items-center justify-center py-12"
    >
      <UIcon
        name="i-lucide-loader-2"
        class="size-8 animate-spin text-muted"
      />
    </div>

    <!-- Empty -->
    <div
      v-else-if="shares.length === 0"
      class="text-center py-12 text-muted"
    >
      <UIcon
        name="i-lucide-share-2"
        class="size-12 mx-auto mb-4 opacity-50"
      />
      <p>{{ t('adminShare.empty') }}</p>
    </div>

    <!-- Table + Pagination -->
    <template v-else>
      <UTable
        :data="shares"
        :columns="columns"
      />

      <div
        v-if="total > pageSize"
        class="flex justify-center"
      >
        <UPagination
          v-model:page="page"
          :total="total"
          :items-per-page="pageSize"
          show-edges
        />
      </div>
    </template>
  </div>

  <!-- Detail Modal -->
  <UModal
    v-model:open="detailModalOpen"
    :title="t('adminShare.detailTitle')"
    description=" "
    :ui="{ footer: 'justify-end', content: 'sm:max-w-lg', description: 'hidden' }"
  >
    <template #body>
      <div
        v-if="detailLoading"
        class="flex justify-center py-8"
      >
        <UIcon
          name="i-lucide-loader-2"
          class="size-6 animate-spin text-muted"
        />
      </div>
      <div
        v-else-if="shareDetail"
        class="space-y-3 text-sm"
      >
        <div class="flex justify-between">
          <span class="text-muted">{{ t('adminShare.code') }}</span>
          <span class="font-mono">{{ shareDetail.code }}</span>
        </div>
        <USeparator />
        <div class="flex justify-between">
          <span class="text-muted">{{ t('adminShare.username') }}</span>
          <span>{{ shareDetail.username || '-' }}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-muted">{{ t('adminShare.hasPassword') }}</span>
          <span>{{ shareDetail.has_password ? t('adminShare.yes') : t('adminShare.no') }}</span>
        </div>
        <USeparator />
        <div class="flex justify-between">
          <span class="text-muted">{{ t('adminShare.viewsDownloads') }}</span>
          <span>{{ shareDetail.views }} / {{ shareDetail.downloads }}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-muted">{{ t('adminShare.downloadLimit') }}</span>
          <span>{{ shareDetail.remain_downloads != null ? shareDetail.remain_downloads : t('adminShare.unlimited') }}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-muted">{{ t('adminShare.preview') }}</span>
          <UBadge
            :label="shareDetail.preview_enabled ? t('adminShare.previewOn') : t('adminShare.previewOff')"
            :color="shareDetail.preview_enabled ? 'success' : 'neutral'"
            variant="subtle"
            size="md"
          />
        </div>
        <div class="flex justify-between">
          <span class="text-muted">{{ t('adminShare.score') }}</span>
          <span>{{ shareDetail.score }}</span>
        </div>
        <USeparator />
        <div class="flex justify-between">
          <span class="text-muted">{{ t('adminShare.expires') }}</span>
          <span>{{ shareDetail.expires ? formatDate(shareDetail.expires) : t('adminShare.neverExpire') }}</span>
        </div>
        <div class="flex justify-between">
          <span class="text-muted">{{ t('adminShare.createdAt') }}</span>
          <span>{{ formatDate(shareDetail.created_at) }}</span>
        </div>
      </div>
    </template>

    <template #footer>
      <UButton
        :label="t('common.cancel')"
        color="neutral"
        variant="outline"
        @click="detailModalOpen = false"
      />
    </template>
  </UModal>

  <!-- Delete Confirmation Modal -->
  <UModal
    v-model:open="deleteModalOpen"
    :title="t('adminShare.deleteShare')"
    description=" "
    :ui="{ footer: 'justify-end', description: 'hidden' }"
  >
    <template #body>
      <p class="text-sm">
        {{ t('adminShare.deleteConfirm', { name: deletingShare?.object_name || deletingShare?.code }) }}
      </p>
    </template>

    <template #footer>
      <UButton
        :label="t('common.cancel')"
        color="neutral"
        variant="outline"
        @click="deleteModalOpen = false"
      />
      <UButton
        :label="t('common.delete')"
        color="error"
        :loading="deleting"
        @click="confirmDelete"
      />
    </template>
  </UModal>
</template>

// src/pages/shares.tsx
import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter,
  DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { Copy, Trash2, Link2, Loader2, ChevronLeft, ChevronRight } from "lucide-react";
import { share, resolveErrorMessage, ApiError } from "@/api";
import type { ShareResponse } from "@/api";

const PAGE_SIZE = 20;

type FilterTab = "all" | "active" | "expired";

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    year: "numeric", month: "2-digit", day: "2-digit",
    hour: "2-digit", minute: "2-digit",
  });
}

export default function SharesPage() {
  const { t } = useTranslation();
  const [items, setItems] = useState<ShareResponse[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(0);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<FilterTab>("all");

  // Delete dialog
  const [deleteTarget, setDeleteTarget] = useState<ShareResponse | null>(null);
  const [deleting, setDeleting] = useState(false);

  const loadShares = useCallback(async () => {
    setLoading(true);
    try {
      const expired = filter === "all" ? undefined : filter === "expired";
      const data = await share.list({
        offset: page * PAGE_SIZE,
        limit: PAGE_SIZE,
        expired,
      });
      setItems(data.items);
      setTotal(data.count);
    } catch (err) {
      const msg = err instanceof ApiError ? err.message : t("common.loading");
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  }, [page, filter, t]);

  useEffect(() => {
    loadShares();
  }, [loadShares]);

  const handleFilterChange = (value: string) => {
    setFilter(value as FilterTab);
    setPage(0);
  };

  const handleCopyLink = (code: string) => {
    const url = `${window.location.origin}/s/${code}`;
    navigator.clipboard.writeText(url).then(() => {
      toast.success(t("share.linkCopied"));
    });
  };

  const handleDelete = async () => {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      await share.delete(deleteTarget.id);
      toast.success(t("share.deleteSuccess"));
      setDeleteTarget(null);
      loadShares();
    } catch (err) {
      toast.error(resolveErrorMessage(err));
    } finally {
      setDeleting(false);
    }
  };

  const totalPages = Math.ceil(total / PAGE_SIZE);

  return (
    <div className="flex flex-1 flex-col gap-4">
      <div className="flex items-center justify-between">
        <Tabs value={filter} onValueChange={handleFilterChange}>
          <TabsList>
            <TabsTrigger value="all">{t("share.all")}</TabsTrigger>
            <TabsTrigger value="active">{t("share.active")}</TabsTrigger>
            <TabsTrigger value="expired">{t("share.expired")}</TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {loading ? (
        <div className="flex flex-col gap-3">
          {Array.from({ length: 5 }).map((_, i) => (
            <div key={i} className="flex items-center gap-3">
              <Skeleton className="h-5 flex-1" />
              <Skeleton className="h-5 w-12" />
              <Skeleton className="h-5 w-12" />
              <Skeleton className="h-5 w-20" />
              <Skeleton className="h-5 w-28" />
              <Skeleton className="h-5 w-16" />
            </div>
          ))}
        </div>
      ) : items.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <Link2 />
            </EmptyMedia>
            <EmptyTitle>{t("share.noShares")}</EmptyTitle>
            <EmptyDescription>{t("share.noSharesHint")}</EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t("file.name")}</TableHead>
                <TableHead className="w-16 text-right">{t("share.views")}</TableHead>
                <TableHead className="w-16 text-right">{t("share.downloads")}</TableHead>
                <TableHead className="w-28">{t("share.status")}</TableHead>
                <TableHead className="w-40 text-right">{t("share.createdAt")}</TableHead>
                <TableHead className="w-24 text-right">{t("share.actions")}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((item) => (
                <TableRow key={item.id}>
                  <TableCell className="font-medium">
                    <span className="truncate">{item.file_id.slice(0, 8)}…</span>
                  </TableCell>
                  <TableCell className="text-right text-muted-foreground">{item.views}</TableCell>
                  <TableCell className="text-right text-muted-foreground">{item.downloads}</TableCell>
                  <TableCell>
                    <div className="flex gap-1">
                      {item.is_expired ? (
                        <Badge variant="destructive">{t("share.expired")}</Badge>
                      ) : item.expires ? (
                        <Badge variant="secondary">{t("share.active")}</Badge>
                      ) : (
                        <Badge variant="outline">{t("share.permanent")}</Badge>
                      )}
                      {item.has_password && (
                        <Badge variant="outline">{t("share.hasPassword")}</Badge>
                      )}
                    </div>
                  </TableCell>
                  <TableCell className="text-right text-muted-foreground">
                    {formatDate(item.created_at)}
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-1">
                      <Button variant="ghost" size="icon" className="size-8" onClick={() => handleCopyLink(item.code)}>
                        <Copy className="size-4" />
                      </Button>
                      <Button variant="ghost" size="icon" className="size-8 text-destructive" onClick={() => setDeleteTarget(item)}>
                        <Trash2 className="size-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          {totalPages > 1 && (
            <div className="flex items-center justify-center gap-2">
              <Button variant="outline" size="icon" className="size-8" disabled={page === 0} onClick={() => setPage(page - 1)}>
                <ChevronLeft className="size-4" />
              </Button>
              <span className="text-sm text-muted-foreground">
                {page + 1} / {totalPages}
              </span>
              <Button variant="outline" size="icon" className="size-8" disabled={page >= totalPages - 1} onClick={() => setPage(page + 1)}>
                <ChevronRight className="size-4" />
              </Button>
            </div>
          )}
        </>
      )}

      {/* Delete confirmation dialog */}
      <Dialog open={!!deleteTarget} onOpenChange={(v) => { if (!v) setDeleteTarget(null); }}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{t("share.deleteShare")}</DialogTitle>
            <DialogDescription>{t("share.deleteConfirm")}</DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteTarget(null)} disabled={deleting}>
              {t("common.cancel")}
            </Button>
            <Button variant="destructive" onClick={handleDelete} disabled={deleting}>
              {deleting && <Loader2 className="mr-2 size-4 animate-spin" />}
              {t("common.delete")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
