// src/pages/admin/home.tsx
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  ChartLegend,
  ChartLegendContent,
  type ChartConfig,
} from "@/components/ui/chart";
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts";
import { FileIcon, Users, Share2, Database } from "lucide-react";
import { admin, resolveErrorMessage } from "@/api";
import type { AdminSummaryResponse } from "@/api";

export default function AdminHomePage() {
  const { t } = useTranslation();
  const [data, setData] = useState<AdminSummaryResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await admin.summary();
        setData(res);
      } catch (e) {
        toast.error(resolveErrorMessage(e));
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const chartConfig: ChartConfig = {
    files: { label: t("adminHome.files"), color: "oklch(0.6 0.18 250)" },
    users: { label: t("adminHome.users"), color: "oklch(0.6 0.18 150)" },
    shares: { label: t("adminHome.shares"), color: "oklch(0.6 0.18 30)" },
  };

  const chartData = data?.metrics_summary.dates.map((date, i) => ({
    date,
    files: data.metrics_summary.files[i],
    users: data.metrics_summary.users[i],
    shares: data.metrics_summary.shares[i],
  })) ?? [];

  const formatDate = (iso: string) => {
    const d = new Date(iso);
    return `${(d.getMonth() + 1).toString().padStart(2, "0")}/${d.getDate().toString().padStart(2, "0")}`;
  };

  const formatDateTime = (iso: string) =>
    new Date(iso).toLocaleString(undefined, {
      year: "numeric", month: "2-digit", day: "2-digit",
      hour: "2-digit", minute: "2-digit",
    });

  const isLicenseExpired = data ? new Date(data.license.expired_at) < new Date() : false;

  if (loading) {
    return (
      <div className="space-y-6 p-6">
        <Skeleton className="h-8 w-48" />
        <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-28" />
          ))}
        </div>
        <Skeleton className="h-72" />
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          <Skeleton className="h-48" />
          <Skeleton className="h-48" />
        </div>
      </div>
    );
  }

  if (!data) return null;

  const stats = [
    { label: t("adminHome.totalFiles"), value: data.metrics_summary.file_total, icon: FileIcon },
    { label: t("adminHome.totalUsers"), value: data.metrics_summary.user_total, icon: Users },
    { label: t("adminHome.totalShares"), value: data.metrics_summary.share_total, icon: Share2 },
    { label: t("adminHome.totalEntities"), value: data.metrics_summary.entities_total, icon: Database },
  ];

  return (
    <div className="space-y-6 p-6">
      <h1 className="text-2xl font-bold">{t("adminHome.title")}</h1>

      {/* Stat Cards */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        {stats.map((stat) => (
          <Card key={stat.label}>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardDescription className="text-sm font-medium">{stat.label}</CardDescription>
              <stat.icon className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stat.value.toLocaleString()}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Trend Chart */}
      {chartData.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>{t("adminHome.trendChart")}</CardTitle>
          </CardHeader>
          <CardContent>
            <ChartContainer config={chartConfig} className="h-64 w-full">
              <AreaChart data={chartData} margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis
                  dataKey="date"
                  tickFormatter={formatDate}
                  tickLine={false}
                  axisLine={false}
                  fontSize={12}
                />
                <YAxis tickLine={false} axisLine={false} fontSize={12} width={40} />
                <ChartTooltip content={<ChartTooltipContent />} />
                <ChartLegend content={<ChartLegendContent />} />
                <Area
                  type="monotone"
                  dataKey="files"
                  stroke="var(--color-files)"
                  fill="var(--color-files)"
                  fillOpacity={0.15}
                  strokeWidth={2}
                />
                <Area
                  type="monotone"
                  dataKey="users"
                  stroke="var(--color-users)"
                  fill="var(--color-users)"
                  fillOpacity={0.15}
                  strokeWidth={2}
                />
                <Area
                  type="monotone"
                  dataKey="shares"
                  stroke="var(--color-shares)"
                  fill="var(--color-shares)"
                  fillOpacity={0.15}
                  strokeWidth={2}
                />
              </AreaChart>
            </ChartContainer>
          </CardContent>
        </Card>
      )}

      {/* Info Cards */}
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {/* License Card */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              {t("adminHome.license")}
              <Badge variant={isLicenseExpired ? "destructive" : "secondary"}>
                {isLicenseExpired ? t("adminHome.expired") : t("adminHome.valid")}
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">{t("adminHome.expiredAt")}</span>
              <span>{formatDateTime(data.license.expired_at)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">{t("adminHome.signedAt")}</span>
              <span>{formatDateTime(data.license.signed_at)}</span>
            </div>
            {data.license.root_domains.length > 0 && (
              <div>
                <span className="text-muted-foreground">{t("adminHome.rootDomains")}</span>
                <div className="mt-1 flex flex-wrap gap-1">
                  {data.license.root_domains.map((d) => (
                    <Badge key={d} variant="outline">{d}</Badge>
                  ))}
                </div>
              </div>
            )}
            {data.license.domains.length > 0 && (
              <div>
                <span className="text-muted-foreground">{t("adminHome.domains")}</span>
                <div className="mt-1 flex flex-wrap gap-1">
                  {data.license.domains.map((d) => (
                    <Badge key={d} variant="outline">{d}</Badge>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Version Card */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              {t("adminHome.version")}
              <Badge variant={data.version.pro ? "default" : "secondary"}>
                {data.version.pro ? t("adminHome.pro") : t("adminHome.community")}
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">{t("adminHome.version")}</span>
              <span className="font-mono">{data.version.version}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">{t("adminHome.commit")}</span>
              <span className="font-mono text-xs">{data.version.commit}</span>
            </div>
            {data.site_urls.length > 0 && (
              <div>
                <span className="text-muted-foreground">{t("adminHome.siteUrls")}</span>
                <div className="mt-1 flex flex-wrap gap-1">
                  {data.site_urls.map((url) => (
                    <Badge key={url} variant="outline">{url}</Badge>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Footer */}
      <p className="text-xs text-muted-foreground">
        {t("adminHome.generatedAt", { time: formatDateTime(data.metrics_summary.generated_at) })}
      </p>
    </div>
  );
}

// src/pages/admin/home.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { Line } from 'vue-chartjs'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js'
import api from '../../utils/api'

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend, Filler)

const { t } = useI18n()

interface AdminSummary {
  version: {
    version: string
    pro: boolean
    commit: string
  }
  license: {
    expired_at: string
    signed_at: string
  }
  site_urls: string[]
  metrics_summary: {
    file_total: number
    user_total: number
    share_total: number
    entities_total: number
    dates: string[]
    files: number[]
    users: number[]
    shares: number[]
    generated_at: string
  }
}

const summary = ref<AdminSummary | null>(null)
const loading = ref(true)
const error = ref('')

onMounted(async () => {
  try {
    const { data } = await api.get<AdminSummary>('/api/v1/admin/summary')
    summary.value = data
  } catch {
    error.value = t('admin.loadError')
  } finally {
    loading.value = false
  }
})

const generatedAgo = computed(() => {
  if (!summary.value?.metrics_summary.generated_at) return ''
  const diff = Date.now() - new Date(summary.value.metrics_summary.generated_at).getTime()
  const minutes = Math.max(1, Math.floor(diff / 60000))
  if (minutes < 60) return t('admin.generatedAgo', { n: minutes })
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return t('admin.generatedAgoHours', { n: hours })
  return t('admin.generatedAgoDays', { n: Math.floor(hours / 24) })
})

const chartData = computed(() => {
  if (!summary.value) return null
  const m = summary.value.metrics_summary
  return {
    labels: m.dates.map((d) => d.slice(5)),
    datasets: [
      {
        label: t('admin.users'),
        data: m.users,
        borderColor: 'rgb(59, 130, 246)',
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        fill: true,
        tension: 0.3
      },
      {
        label: t('admin.files'),
        data: m.files,
        borderColor: 'rgb(245, 158, 11)',
        backgroundColor: 'rgba(245, 158, 11, 0.1)',
        fill: true,
        tension: 0.3
      },
      {
        label: t('admin.shares'),
        data: m.shares,
        borderColor: 'rgb(16, 185, 129)',
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        fill: true,
        tension: 0.3
      }
    ]
  }
})

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  interaction: {
    intersect: false,
    mode: 'index' as const
  },
  plugins: {
    legend: {
      position: 'bottom' as const
    }
  },
  scales: {
    y: {
      beginAtZero: true
    }
  }
}

const statsItems = computed(() => {
  if (!summary.value) return []
  const m = summary.value.metrics_summary
  return [
    { icon: 'i-lucide-users', color: 'primary' as const, value: m.user_total, label: t('admin.users') },
    { icon: 'i-lucide-file', color: 'warning' as const, value: m.file_total, label: t('admin.files') },
    { icon: 'i-lucide-share-2', color: 'success' as const, value: m.share_total, label: t('admin.shares') },
    { icon: 'i-lucide-binary', color: 'error' as const, value: m.entities_total, label: t('admin.fileBlobs') }
  ]
})

function formatDate(iso: string): string {
  if (!iso) return '-'
  return new Date(iso).toLocaleDateString()
}
</script>

<template>
  <div class="p-6 space-y-6">
    <h1 class="text-2xl font-semibold">
      {{ t('admin.siteSummary') }}
    </h1>

    <div
      v-if="loading"
      class="flex items-center justify-center py-12"
    >
      <UIcon
        name="i-lucide-loader-2"
        class="size-8 animate-spin text-muted"
      />
    </div>

    <div
      v-else-if="error"
      class="text-center py-12 text-red-500"
    >
      {{ error }}
    </div>

    <template v-else-if="summary">
      <!-- Trend chart + Stats summary (3:1) -->
      <div class="grid grid-cols-1 lg:grid-cols-4 gap-4">
        <UCard class="lg:col-span-3">
          <template #header>
            <div class="flex items-center justify-between">
              <span class="font-semibold">{{ t('admin.trend') }}</span>
              <span class="text-sm text-muted">{{ generatedAgo }}</span>
            </div>
          </template>
          <div
            v-if="chartData"
            class="h-72"
          >
            <Line
              :data="chartData"
              :options="chartOptions"
            />
          </div>
        </UCard>

        <UCard>
          <template #header>
            <span class="font-semibold">{{ t('admin.total') }}</span>
          </template>
          <div class="space-y-5">
            <div
              v-for="item in statsItems"
              :key="item.label"
              class="flex items-center gap-3"
            >
              <UAvatar
                :icon="item.icon"
                :color="item.color"
                size="lg"
              />
              <div>
                <p class="text-lg font-bold leading-tight">
                  {{ item.value.toLocaleString() }}
                </p>
                <p class="text-sm text-muted">
                  {{ item.label }}
                </p>
              </div>
            </div>
          </div>
        </UCard>
      </div>

      <!-- Info cards -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <UCard>
          <div class="space-y-1">
            <p class="text-sm text-muted">
              {{ t('admin.version') }}
            </p>
            <p class="font-medium">
              {{ summary.version.version }}
              <UBadge
                v-if="summary.version.pro"
                color="primary"
                variant="subtle"
                size="md"
              >
                Pro
              </UBadge>
            </p>
            <p class="text-xs text-muted font-mono">
              {{ summary.version.commit }}
            </p>
          </div>
        </UCard>

        <UCard>
          <div class="space-y-1">
            <p class="text-sm text-muted">
              {{ t('admin.license') }}
            </p>
            <p class="text-sm">
              {{ t('admin.expiresAt', { date: formatDate(summary.license.expired_at) }) }}
            </p>
            <p class="text-xs text-muted">
              {{ t('admin.signedAt', { date: formatDate(summary.license.signed_at) }) }}
            </p>
          </div>
        </UCard>

        <UCard>
          <div class="space-y-1">
            <p class="text-sm text-muted">
              {{ t('admin.siteUrls') }}
            </p>
            <p
              v-for="url in summary.site_urls"
              :key="url"
              class="text-sm truncate"
            >
              {{ url }}
            </p>
          </div>
        </UCard>
      </div>
    </template>
  </div>
</template>
