// src/pages/admin/users.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router";
import { toast } from "sonner";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter,
  DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { Plus, Pencil, Trash2, Loader2, ChevronLeft, ChevronRight, UserIcon } from "lucide-react";
import { adminUser, adminGroup, resolveErrorMessage } from "@/api";
import type { AdminUserResponse, AdminUserCreateRequest, AdminGroupResponse, UserStatus } from "@/api";

const PAGE_SIZE = 20;

function formatBytes(bytes: number): string {
  if (bytes === 0) return "0";
  const units = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  return `${(bytes / Math.pow(1024, i)).toFixed(i > 0 ? 1 : 0)} ${units[i]}`;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    year: "numeric", month: "2-digit", day: "2-digit",
    hour: "2-digit", minute: "2-digit",
  });
}

const STATUS_VARIANTS: Record<string, "default" | "secondary" | "destructive" | "outline"> = {
  active: "secondary",
  admin_banned: "destructive",
  system_banned: "destructive",
};

export default function AdminUsersPage() {
  const { t } = useTranslation();
  const navigate = useNavigate();

  const [users, setUsers] = useState<AdminUserResponse[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(0);
  const [loading, setLoading] = useState(true);
  const [groups, setGroups] = useState<AdminGroupResponse[]>([]);

  // Filters
  const [emailFilter, setEmailFilter] = useState("");
  const [nicknameFilter, setNicknameFilter] = useState("");
  const [groupFilter, setGroupFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Selection
  const [selected, setSelected] = useState<Set<string>>(new Set());

  // Create dialog
  const [createOpen, setCreateOpen] = useState(false);
  const [formEmail, setFormEmail] = useState("");
  const [formPassword, setFormPassword] = useState("");
  const [formNickname, setFormNickname] = useState("");
  const [formGroupId, setFormGroupId] = useState("");
  const [submitting, setSubmitting] = useState(false);

  // Delete dialog
  const [deleteIds, setDeleteIds] = useState<string[]>([]);
  const [deleting, setDeleting] = useState(false);

  const loadUsers = useCallback(async () => {
    setLoading(true);
    try {
      const data = await adminUser.list({
        offset: page * PAGE_SIZE,
        limit: PAGE_SIZE,
        email_contains: emailFilter || undefined,
        nickname_contains: nicknameFilter || undefined,
        group_id: groupFilter || undefined,
        status: (statusFilter as UserStatus) || undefined,
      });
      setUsers(data.items);
      setTotal(data.count);
    } catch (err) {
      toast.error(resolveErrorMessage(err));
    } finally {
      setLoading(false);
    }
  }, [page, emailFilter, nicknameFilter, groupFilter, statusFilter]);

  useEffect(() => {
    loadUsers();
  }, [loadUsers]);

  // Load groups for filter & create dialog
  useEffect(() => {
    adminGroup.list({ limit: 200 }).then((data) => {
      setGroups(data.items);
    }).catch(() => {});
  }, []);

  // Debounced filter change
  const handleEmailChange = (v: string) => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      setEmailFilter(v);
      setPage(0);
    }, 300);
  };

  const handleNicknameChange = (v: string) => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      setNicknameFilter(v);
      setPage(0);
    }, 300);
  };

  const handleGroupFilterChange = (v: string | null) => {
    setGroupFilter(!v || v === "__all__" ? "" : v);
    setPage(0);
  };

  const handleStatusFilterChange = (v: string | null) => {
    setStatusFilter(!v || v === "__all__" ? "" : v);
    setPage(0);
  };

  const toggleSelect = (id: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const toggleSelectAll = () => {
    if (selected.size === users.length) {
      setSelected(new Set());
    } else {
      setSelected(new Set(users.map((u) => u.id)));
    }
  };

  const openCreateDialog = () => {
    setFormEmail("");
    setFormPassword("");
    setFormNickname("");
    setFormGroupId(groups[0]?.id ?? "");
    setCreateOpen(true);
  };

  const handleCreate = async () => {
    if (!formEmail.trim() || !formNickname.trim() || !formGroupId) return;
    setSubmitting(true);
    try {
      const req: AdminUserCreateRequest = {
        email: formEmail.trim(),
        password: formPassword || undefined,
        nickname: formNickname.trim(),
        group_id: formGroupId,
      };
      await adminUser.create(req);
      toast.success(t("adminUser.createSuccess"));
      setCreateOpen(false);
      loadUsers();
    } catch (err) {
      toast.error(resolveErrorMessage(err));
    } finally {
      setSubmitting(false);
    }
  };

  const handleBatchDelete = async () => {
    if (deleteIds.length === 0) return;
    setDeleting(true);
    try {
      await adminUser.delete(deleteIds);
      toast.success(t("adminUser.deleteSuccess", { count: deleteIds.length }));
      setDeleteIds([]);
      setSelected(new Set());
      loadUsers();
    } catch (err) {
      toast.error(resolveErrorMessage(err));
    } finally {
      setDeleting(false);
    }
  };

  const totalPages = Math.ceil(total / PAGE_SIZE);

  const statusLabel = (status: string) => {
    const map: Record<string, string> = {
      active: t("adminUser.statusActive"),
      admin_banned: t("adminUser.statusAdminBanned"),
      system_banned: t("adminUser.statusSystemBanned"),
    };
    return map[status] ?? status;
  };

  return (
    <div className="flex flex-1 flex-col gap-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold">{t("adminUser.title")}</h2>
        <div className="flex items-center gap-2">
          {selected.size > 0 && (
            <>
              <span className="text-sm text-muted-foreground">
                {t("adminUser.selectedCount", { count: selected.size })}
              </span>
              <Button variant="destructive" size="sm" onClick={() => setDeleteIds([...selected])}>
                <Trash2 className="mr-2 size-4" />
                {t("adminUser.batchDelete")}
              </Button>
            </>
          )}
          <Button size="sm" onClick={openCreateDialog}>
            <Plus className="mr-2 size-4" />
            {t("adminUser.createUser")}
          </Button>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-end gap-3">
        <div className="grid gap-1">
          <Label className="text-xs">{t("adminUser.filterByEmail")}</Label>
          <Input className="h-8 w-48" placeholder={t("adminUser.emailPlaceholder")} onChange={(e) => handleEmailChange(e.target.value)} />
        </div>
        <div className="grid gap-1">
          <Label className="text-xs">{t("adminUser.filterByNickname")}</Label>
          <Input className="h-8 w-40" placeholder={t("adminUser.nicknamePlaceholder")} onChange={(e) => handleNicknameChange(e.target.value)} />
        </div>
        <div className="grid gap-1">
          <Label className="text-xs">{t("adminUser.filterByGroup")}</Label>
          <Select value={groupFilter || "__all__"} onValueChange={handleGroupFilterChange}>
            <SelectTrigger className="h-8 w-40">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="__all__">{t("adminUser.allGroups")}</SelectItem>
              {groups.map((g) => (
                <SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="grid gap-1">
          <Label className="text-xs">{t("adminUser.filterByStatus")}</Label>
          <Select value={statusFilter || "__all__"} onValueChange={handleStatusFilterChange}>
            <SelectTrigger className="h-8 w-36">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="__all__">{t("adminUser.allStatuses")}</SelectItem>
              <SelectItem value="active">{t("adminUser.statusActive")}</SelectItem>
              <SelectItem value="admin_banned">{t("adminUser.statusAdminBanned")}</SelectItem>
              <SelectItem value="system_banned">{t("adminUser.statusSystemBanned")}</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {loading ? (
        <div className="flex flex-col gap-3">
          {Array.from({ length: 5 }).map((_, i) => (
            <div key={i} className="flex items-center gap-3">
              <Skeleton className="size-4" />
              <Skeleton className="h-5 flex-1" />
              <Skeleton className="h-5 w-24" />
              <Skeleton className="h-5 w-20" />
              <Skeleton className="h-5 w-16" />
              <Skeleton className="h-5 w-28" />
            </div>
          ))}
        </div>
      ) : users.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <UserIcon />
            </EmptyMedia>
            <EmptyTitle>{t("adminUser.noUsers")}</EmptyTitle>
            <EmptyDescription>{t("adminUser.noUsersHint")}</EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-10">
                  <Checkbox
                    checked={selected.size === users.length && users.length > 0}
                    onCheckedChange={toggleSelectAll}
                  />
                </TableHead>
                <TableHead>{t("adminUser.email")}</TableHead>
                <TableHead>{t("adminUser.nickname")}</TableHead>
                <TableHead>{t("adminUser.group")}</TableHead>
                <TableHead className="w-28">{t("adminUser.status")}</TableHead>
                <TableHead className="w-24 text-right">{t("adminUser.storage")}</TableHead>
                <TableHead className="w-40 text-right">{t("adminUser.createdAt")}</TableHead>
                <TableHead className="w-24 text-right">{t("adminUser.actions")}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {users.map((user) => (
                <TableRow key={user.id}>
                  <TableCell>
                    <Checkbox
                      checked={selected.has(user.id)}
                      onCheckedChange={() => toggleSelect(user.id)}
                    />
                  </TableCell>
                  <TableCell>
                    <button
                      className="font-medium text-left hover:underline cursor-pointer"
                      onClick={() => navigate(`/admin/users/${user.id}`)}
                    >
                      {user.email}
                    </button>
                  </TableCell>
                  <TableCell>{user.nickname}</TableCell>
                  <TableCell className="text-muted-foreground">{user.group_name}</TableCell>
                  <TableCell>
                    <Badge variant={STATUS_VARIANTS[user.scopes.includes("admin_banned") ? "admin_banned" : "active"] ?? "outline"}>
                      {statusLabel("active")}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-right text-muted-foreground">
                    {formatBytes(user.storage)}
                  </TableCell>
                  <TableCell className="text-right text-muted-foreground">
                    {formatDate(user.created_at)}
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-1">
                      <Button variant="ghost" size="icon" className="size-8" onClick={() => navigate(`/admin/users/${user.id}`)}>
                        <Pencil className="size-4" />
                      </Button>
                      <Button variant="ghost" size="icon" className="size-8 text-destructive" onClick={() => setDeleteIds([user.id])}>
                        <Trash2 className="size-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          {totalPages > 1 && (
            <div className="flex items-center justify-center gap-2">
              <Button variant="outline" size="icon" className="size-8" disabled={page === 0} onClick={() => setPage(page - 1)}>
                <ChevronLeft className="size-4" />
              </Button>
              <span className="text-sm text-muted-foreground">
                {page + 1} / {totalPages}
              </span>
              <Button variant="outline" size="icon" className="size-8" disabled={page >= totalPages - 1} onClick={() => setPage(page + 1)}>
                <ChevronRight className="size-4" />
              </Button>
            </div>
          )}
        </>
      )}

      {/* Create user dialog */}
      <Dialog open={createOpen} onOpenChange={(v) => { if (!v) setCreateOpen(false); }}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>{t("adminUser.createUser")}</DialogTitle>
            <DialogDescription>{t("adminUser.basicInfoDesc")}</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label>{t("adminUser.email")}</Label>
              <Input type="email" value={formEmail} onChange={(e) => setFormEmail(e.target.value)} placeholder={t("adminUser.emailPlaceholder")} />
            </div>
            <div className="grid gap-2">
              <Label>{t("adminUser.password")}</Label>
              <Input type="password" value={formPassword} onChange={(e) => setFormPassword(e.target.value)} placeholder={t("adminUser.passwordPlaceholder")} />
            </div>
            <div className="grid gap-2">
              <Label>{t("adminUser.nickname")}</Label>
              <Input value={formNickname} onChange={(e) => setFormNickname(e.target.value)} placeholder={t("adminUser.nicknamePlaceholder")} />
            </div>
            <div className="grid gap-2">
              <Label>{t("adminUser.group")}</Label>
              <Select value={formGroupId} onValueChange={(v) => { if (v) setFormGroupId(v); }}>
                <SelectTrigger>
                  <SelectValue placeholder={t("adminUser.selectGroup")} />
                </SelectTrigger>
                <SelectContent>
                  {groups.map((g) => (
                    <SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateOpen(false)} disabled={submitting}>
              {t("common.cancel")}
            </Button>
            <Button onClick={handleCreate} disabled={submitting || !formEmail.trim() || !formNickname.trim() || !formGroupId}>
              {submitting && <Loader2 className="mr-2 size-4 animate-spin" />}
              {t("common.create")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete confirmation */}
      <Dialog open={deleteIds.length > 0} onOpenChange={(v) => { if (!v) setDeleteIds([]); }}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{t("adminUser.deleteUser")}</DialogTitle>
            <DialogDescription>{t("adminUser.deleteConfirm", { count: deleteIds.length })}</DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteIds([])} disabled={deleting}>
              {t("common.cancel")}
            </Button>
            <Button variant="destructive" onClick={handleBatchDelete} disabled={deleting}>
              {deleting && <Loader2 className="mr-2 size-4 animate-spin" />}
              {t("common.delete")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// src/pages/admin/users.vue
<script setup lang="ts">
import { h, ref, computed, onMounted, watch, resolveComponent } from 'vue'
import { useI18n } from 'vue-i18n'
import type { TableColumn, DropdownMenuItem } from '@nuxt/ui'
import type { AxiosError } from 'axios'
import api from '../../utils/api'

type ApiErrorResponse = { detail?: string }

const UBadge = resolveComponent('UBadge')
const UDropdownMenu = resolveComponent('UDropdownMenu')
const UAvatar = resolveComponent('UAvatar')

const { t } = useI18n()
const toast = useToast()

interface User {
  id: string
  email: string
  nickname: string
  status: 'active' | 'admin_banned' | 'system_banned'
  score: number
  storage: number
  avatar: string
  group_expires: string | null
  group_id: string
  group_name: string
  created_at: string
  updated_at: string
}

interface UserListResponse {
  count: number
  items: User[]
}

interface SimpleGroup {
  id: string
  name: string
}

interface CalibrateResponse {
  user_id: string
  previous_storage: number
  current_storage: number
  difference: number
  file_count: number
}

// Group list (for filters & form selects)
const groupList = ref<SimpleGroup[]>([])
const groupSelectItems = computed(() =>
  groupList.value.map(g => ({ label: g.name, value: g.id }))
)

const groupFormItems = computed(() =>
  groupList.value.map(g => ({ label: g.name, value: g.id }))
)

async function fetchGroupList() {
  try {
    const { data } = await api.get<{ groups?: SimpleGroup[]; total?: number; items?: SimpleGroup[]; count?: number }>('/api/v1/admin/group/', {
      params: { offset: 0, limit: 100 }
    })
    groupList.value = data.groups ?? data.items ?? []
  } catch (e: unknown) {
    const err = e as AxiosError<ApiErrorResponse>
    toast.add({
      title: t('group.loadFailed'),
      description: err.response?.data?.detail || '',
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
  }
}

// List state
const users = ref<User[]>([])
const total = ref(0)
const loading = ref(true)
const page = ref(1)
const pageSize = 20
const orderBy = ref('created_at')
const orderDesc = ref(true)
const searchQuery = ref('')
const filterGroupId = ref('')
const filterStatus = ref('')

const orderOptions = [
  { label: t('adminUser.orderCreatedAt'), value: 'created_at' },
  { label: t('adminUser.orderUpdatedAt'), value: 'updated_at' }
]

const statusFilterItems = [
  { label: t('adminUser.statusActive'), value: 'active' },
  { label: t('adminUser.statusAdminBanned'), value: 'admin_banned' },
  { label: t('adminUser.statusSystemBanned'), value: 'system_banned' }
]

// Debounced search
const debouncedSearch = ref('')
let searchTimer: ReturnType<typeof setTimeout> | undefined
watch(searchQuery, (val) => {
  clearTimeout(searchTimer)
  searchTimer = setTimeout(() => { debouncedSearch.value = val }, 300)
})

function formatSize(bytes: number): string {
  if (bytes === 0) return '-'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(1024))
  return `${(bytes / Math.pow(1024, i)).toFixed(1)} ${units[i]}`
}

function formatDate(iso: string): string {
  if (!iso) return '-'
  const d = new Date(iso)
  return d.toLocaleDateString(undefined, { year: 'numeric', month: '2-digit', day: '2-digit' })
}

async function fetchUsers() {
  loading.value = true
  try {
    const params: Record<string, unknown> = {
      offset: (page.value - 1) * pageSize,
      limit: pageSize,
      order: orderBy.value,
      desc: orderDesc.value
    }
    if (debouncedSearch.value) {
      params.email = debouncedSearch.value
      params.nickname = debouncedSearch.value
    }
    if (filterGroupId.value) params.group_id = filterGroupId.value
    if (filterStatus.value) params.status = filterStatus.value

    const { data } = await api.get<UserListResponse>('/api/v1/admin/user/list', { params })
    users.value = data.items
    total.value = data.count
  } catch (e: unknown) {
    const err = e as AxiosError<ApiErrorResponse>
    toast.add({
      title: t('adminUser.loadFailed'),
      description: err.response?.data?.detail || '',
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
  } finally {
    loading.value = false
  }
}

watch(page, () => fetchUsers())
watch([debouncedSearch, filterGroupId, filterStatus, orderBy, orderDesc], () => {
  page.value = 1
  fetchUsers()
})

onMounted(() => {
  fetchGroupList()
  fetchUsers()
})

// Status badge config
const statusConfig: Record<string, { color: 'success' | 'error' | 'warning'; key: string }> = {
  active: { color: 'success', key: 'adminUser.statusActive' },
  admin_banned: { color: 'error', key: 'adminUser.statusAdminBanned' },
  system_banned: { color: 'warning', key: 'adminUser.statusSystemBanned' }
}

// Table columns
function getDropdownItems(user: User): DropdownMenuItem[][] {
  return [
    [
      {
        label: t('common.edit'),
        icon: 'i-lucide-pencil',
        onSelect() { openEditModal(user) }
      },
      {
        label: t('adminUser.calibrate'),
        icon: 'i-lucide-hard-drive',
        onSelect() { calibrateUser(user) }
      }
    ],
    [
      {
        label: t('common.delete'),
        icon: 'i-lucide-trash-2',
        color: 'error' as const,
        onSelect() { openDeleteModal(user) }
      }
    ]
  ]
}

const columns = computed<TableColumn<User>[]>(() => [
  {
    id: 'user',
    header: t('adminUser.email'),
    cell: ({ row }) => {
      return h('div', { class: 'flex items-center gap-3' }, [
        h(UAvatar, { src: `/api/v1/user/avatar/${row.original.id}/64`, alt: row.original.nickname || row.original.email, size: 'sm' }),
        h('div', { class: 'min-w-0' }, [
          h('div', { class: 'font-medium truncate' }, row.original.email),
          h('div', { class: 'text-xs text-muted truncate' }, row.original.nickname || '-')
        ])
      ])
    }
  },
  {
    accessorKey: 'status',
    header: t('adminUser.status'),
    cell: ({ row }) => {
      const cfg = statusConfig[row.original.status]
      if (!cfg) return row.original.status
      return h(UBadge, { color: cfg.color, variant: 'subtle', size: 'md' }, { default: () => t(cfg.key) })
    }
  },
  {
    accessorKey: 'group_name',
    header: t('adminUser.group')
  },
  {
    accessorKey: 'storage',
    header: t('adminUser.storage'),
    cell: ({ row }) => formatSize(row.original.storage)
  },
  {
    accessorKey: 'score',
    header: t('adminUser.score')
  },
  {
    accessorKey: 'created_at',
    header: t('adminUser.createdAt'),
    cell: ({ row }) => formatDate(row.original.created_at)
  },
  {
    id: 'actions',
    header: t('adminUser.actions'),
    cell: ({ row }) => {
      return h(UDropdownMenu, {
        items: getDropdownItems(row.original),
        content: { align: 'end' }
      }, {
        default: () => h(resolveComponent('UButton'), {
          icon: 'i-lucide-ellipsis-vertical',
          color: 'neutral',
          variant: 'ghost',
          size: 'xs'
        })
      })
    }
  }
])

// Create/Edit Modal
const formModalOpen = ref(false)
const editingUser = ref<User | null>(null)
const submitting = ref(false)

const formData = ref({
  email: '',
  password: '',
  nickname: '',
  group_id: '',
  status: 'active' as string,
  score: 0,
  storage: 0,
  group_expires: ''
})

const isEditing = computed(() => !!editingUser.value)

const storageGB = computed({
  get: () => formData.value.storage / (1024 * 1024 * 1024),
  set: (v: number | null) => { formData.value.storage = (v ?? 0) * 1024 * 1024 * 1024 }
})

const statusFormItems = [
  { label: t('adminUser.statusActive'), value: 'active' },
  { label: t('adminUser.statusAdminBanned'), value: 'admin_banned' },
  { label: t('adminUser.statusSystemBanned'), value: 'system_banned' }
]

function resetForm() {
  formData.value = {
    email: '',
    password: '',
    nickname: '',
    group_id: groupList.value.length ? groupList.value[0].id : '',
    status: 'active',
    score: 0,
    storage: 0,
    group_expires: ''
  }
}

function openCreateModal() {
  editingUser.value = null
  resetForm()
  formModalOpen.value = true
}

function openEditModal(user: User) {
  editingUser.value = user
  formData.value = {
    email: user.email,
    password: '',
    nickname: user.nickname,
    group_id: user.group_id,
    status: user.status,
    score: user.score,
    storage: user.storage,
    group_expires: user.group_expires ? user.group_expires.slice(0, 16) : ''
  }
  formModalOpen.value = true
}

async function submitForm() {
  if (!formData.value.email.trim()) return
  submitting.value = true
  try {
    if (isEditing.value) {
      const body: Record<string, unknown> = {
        email: formData.value.email,
        nickname: formData.value.nickname,
        group_id: formData.value.group_id,
        status: formData.value.status,
        score: formData.value.score,
        storage: formData.value.storage,
        group_expires: formData.value.group_expires ? new Date(formData.value.group_expires).toISOString() : null
      }
      await api.patch(`/api/v1/admin/user/${editingUser.value!.id}`, body)
      toast.add({ title: t('adminUser.updateSuccess'), icon: 'i-lucide-check-circle', color: 'success' })
    } else {
      if (!formData.value.password.trim()) return
      await api.post('/api/v1/admin/user/create', {
        email: formData.value.email,
        password: formData.value.password,
        nickname: formData.value.nickname,
        group_id: formData.value.group_id,
        status: formData.value.status
      })
      toast.add({ title: t('adminUser.createSuccess'), icon: 'i-lucide-check-circle', color: 'success' })
    }
    formModalOpen.value = false
    fetchUsers()
  } catch (e: unknown) {
    const err = e as AxiosError<ApiErrorResponse>
    toast.add({
      title: isEditing.value ? t('adminUser.updateFailed') : t('adminUser.createFailed'),
      description: err.response?.data?.detail || '',
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
  } finally {
    submitting.value = false
  }
}

// Delete Modal
const deleteModalOpen = ref(false)
const deletingUser = ref<User | null>(null)
const deleting = ref(false)

function openDeleteModal(user: User) {
  deletingUser.value = user
  deleteModalOpen.value = true
}

async function confirmDelete() {
  if (!deletingUser.value) return
  deleting.value = true
  try {
    await api.delete('/api/v1/admin/user', { data: { ids: [deletingUser.value.id] } })
    toast.add({ title: t('adminUser.deleteSuccess'), icon: 'i-lucide-check-circle', color: 'success' })
    deleteModalOpen.value = false
    fetchUsers()
  } catch (e: unknown) {
    const err = e as AxiosError<ApiErrorResponse>
    toast.add({
      title: t('adminUser.deleteFailed'),
      description: err.response?.data?.detail || '',
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
  } finally {
    deleting.value = false
  }
}

// Calibrate storage
async function calibrateUser(user: User) {
  try {
    const { data } = await api.post<CalibrateResponse>(`/api/v1/admin/user/calibrate/${user.id}`)
    toast.add({
      title: t('adminUser.calibrateSuccess'),
      description: t('adminUser.calibrateResult', {
        previous: formatSize(data.previous_storage),
        current: formatSize(data.current_storage),
        diff: formatSize(Math.abs(data.difference))
      }),
      icon: 'i-lucide-check-circle',
      color: 'success'
    })
    fetchUsers()
  } catch (e: unknown) {
    const err = e as AxiosError<ApiErrorResponse>
    toast.add({
      title: t('adminUser.calibrateFailed'),
      description: err.response?.data?.detail || '',
      icon: 'i-lucide-circle-x',
      color: 'error'
    })
  }
}
</script>

<template>
  <div class="p-6 space-y-6">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <h1 class="text-2xl font-semibold">
        {{ t('adminUser.title') }}
      </h1>
      <div class="flex items-center gap-2">
        <USelect
          v-model="orderBy"
          :items="orderOptions"
          class="w-32"
        />
        <UButton
          :icon="orderDesc ? 'i-lucide-arrow-down-wide-narrow' : 'i-lucide-arrow-up-narrow-wide'"
          color="neutral"
          variant="ghost"
          @click="orderDesc = !orderDesc"
        />
        <UButton
          icon="i-lucide-refresh-cw"
          color="neutral"
          variant="ghost"
          @click="fetchUsers"
        />
        <UButton
          :label="t('adminUser.createUser')"
          icon="i-lucide-plus"
          @click="openCreateModal"
        />
      </div>
    </div>

    <!-- Filters -->
    <div class="flex items-center gap-3">
      <UInput
        v-model="searchQuery"
        :placeholder="t('adminUser.searchPlaceholder')"
        icon="i-lucide-search"
        class="w-64"
      />
      <USelectMenu
        v-model="filterGroupId"
        :items="groupSelectItems"
        value-key="value"
        :placeholder="t('adminUser.allGroups')"
        :search-input="false"
        clear
        class="w-40"
      />
      <USelectMenu
        v-model="filterStatus"
        :items="statusFilterItems"
        value-key="value"
        :placeholder="t('adminUser.allStatuses')"
        :search-input="false"
        clear
        class="w-40"
      />
    </div>

    <!-- Loading -->
    <div
      v-if="loading"
      class="flex items-center justify-center py-12"
    >
      <UIcon
        name="i-lucide-loader-2"
        class="size-8 animate-spin text-muted"
      />
    </div>

    <!-- Table + Pagination -->
    <template v-else>
      <UTable
        :data="users"
        :columns="columns"
      />

      <div
        v-if="total > pageSize"
        class="flex justify-center"
      >
        <UPagination
          v-model:page="page"
          :total="total"
          :items-per-page="pageSize"
          show-edges
        />
      </div>
    </template>
  </div>

  <!-- Create/Edit Modal -->
  <UModal
    v-model:open="formModalOpen"
    :title="isEditing ? t('adminUser.editUser') : t('adminUser.createUser')"
    description=" "
    :ui="{ footer: 'justify-end', content: 'sm:max-w-2xl', description: 'hidden' }"
  >
    <template #body>
      <form @submit.prevent="submitForm">
        <div class="space-y-6">
          <!-- Basic Info -->
          <div class="space-y-4">
            <h3 class="text-sm font-semibold text-muted">
              {{ t('adminUser.basicInfo') }}
            </h3>
            <div class="space-y-3">
              <div>
                <label class="text-sm font-medium mb-1 block">{{ t('adminUser.email') }}</label>
                <UInput
                  v-model="formData.email"
                  type="email"
                  :placeholder="t('adminUser.emailPlaceholder')"
                  class="w-full"
                />
              </div>
              <div>
                <label class="text-sm font-medium mb-1 block">{{ t('adminUser.nickname') }}</label>
                <UInput
                  v-model="formData.nickname"
                  :placeholder="t('adminUser.nicknamePlaceholder')"
                  class="w-full"
                />
              </div>
              <div v-if="!isEditing">
                <label class="text-sm font-medium mb-1 block">{{ t('adminUser.password') }}</label>
                <UInput
                  v-model="formData.password"
                  type="password"
                  :placeholder="t('adminUser.passwordPlaceholder')"
                  class="w-full"
                />
              </div>
            </div>
          </div>

          <USeparator />

          <!-- Account Settings -->
          <div class="space-y-4">
            <h3 class="text-sm font-semibold text-muted">
              {{ t('adminUser.accountSettings') }}
            </h3>
            <div class="space-y-3">
              <div class="grid grid-cols-2 gap-3">
                <div>
                  <label class="text-sm font-medium mb-1 block">{{ t('adminUser.group') }}</label>
                  <USelect
                    v-model="formData.group_id"
                    :items="groupFormItems"
                    class="w-full"
                  />
                </div>
                <div>
                  <label class="text-sm font-medium mb-1 block">{{ t('adminUser.status') }}</label>
                  <USelect
                    v-model="formData.status"
                    :items="statusFormItems"
                    class="w-full"
                  />
                </div>
              </div>

              <template v-if="isEditing">
                <div class="grid grid-cols-2 gap-3">
                  <div>
                    <label class="text-sm font-medium mb-1 block">{{ t('adminUser.score') }}</label>
                    <UInputNumber
                      v-model="formData.score"
                      :min="0"
                      :step="1"
                      class="w-full"
                    />
                  </div>
                  <div>
                    <label class="text-sm font-medium mb-1 block">{{ t('adminUser.storage') }} (GB)</label>
                    <UInputNumber
                      v-model="storageGB"
                      :min="0"
                      :step="0.1"
                      class="w-full"
                    />
                  </div>
                </div>

                <div>
                  <label class="text-sm font-medium mb-1 block">{{ t('adminUser.groupExpires') }}</label>
                  <UInput
                    v-model="formData.group_expires"
                    type="datetime-local"
                    class="w-full"
                  />
                </div>
              </template>
            </div>
          </div>
        </div>
      </form>
    </template>

    <template #footer>
      <UButton
        :label="t('common.cancel')"
        color="neutral"
        variant="outline"
        @click="formModalOpen = false"
      />
      <UButton
        :label="isEditing ? t('common.confirm') : t('common.create')"
        :loading="submitting"
        :disabled="!formData.email.trim() || (!isEditing && !formData.password.trim())"
        @click="submitForm"
      />
    </template>
  </UModal>

  <!-- Delete Confirmation Modal -->
  <UModal
    v-model:open="deleteModalOpen"
    :title="t('adminUser.deleteUser')"
    description=" "
    :ui="{ footer: 'justify-end', description: 'hidden' }"
  >
    <template #body>
      <p class="text-sm">
        {{ t('adminUser.deleteConfirm', { email: deletingUser?.email }) }}
      </p>
    </template>

    <template #footer>
      <UButton
        :label="t('common.cancel')"
        color="neutral"
        variant="outline"
        @click="deleteModalOpen = false"
      />
      <UButton
        :label="t('common.delete')"
        color="error"
        :loading="deleting"
        @click="confirmDelete"
      />
    </template>
  </UModal>
</template>
